/* eslint-disable */
// AUTO-GENERATED by scripts/generate-api-schema.mjs — DO NOT EDIT.
// Source: OpenAPI "KingFisher Wings ERP API" v1.0. Regenerate: npm run gen:api-schema

/** Allowed values per DTO field (OpenAPI `enum`). */
export const API_ENUMS = {
  "UpsertSeaFclBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "UpsertSeaLclBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "UpsertLandBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "UpsertRoadFreightBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "UpsertCourierBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "UpsertCustomsClearanceBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ],
    "direction": [
      "IMPORT",
      "EXPORT",
      "TRANSIT"
    ]
  },
  "UpsertWarehouseBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "cargo_category": [
      "GENERAL",
      "VEHICLES",
      "FOOD_PERISHABLE",
      "PHARMA",
      "CHEMICALS_DG",
      "PERSONAL_EFFECTS",
      "PROJECT_OOG",
      "LIVESTOCK",
      "OTHER"
    ]
  },
  "BookingFormPartyDto": {
    "party_kind": [
      "SHIPPER",
      "CONSIGNEE",
      "NOTIFY",
      "BILLING",
      "AGENT"
    ],
    "entity_kind": [
      "COMPANY",
      "INDIVIDUAL"
    ]
  },
  "ContainerSizeLineDto": {},
  "WhStockLineInputDto": {},
  "CcCargoLineInputDto": {},
  "UpsertAirBookingFormDto": {},
  "AirBookingFormPartyDto": {
    "party_kind": [
      "SHIPPER",
      "CONSIGNEE",
      "NOTIFY"
    ],
    "entity_kind": [
      "COMPANY",
      "INDIVIDUAL"
    ]
  },
  "UpsertAirComplianceBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "activity_sector": [
      "CIVILIAN",
      "MILITARY",
      "NUCLEAR"
    ]
  },
  "AirCompliancePartyDto": {
    "party_kind": [
      "SHIPPER",
      "CONSIGNEE",
      "NOTIFY"
    ],
    "entity_kind": [
      "COMPANY",
      "INDIVIDUAL"
    ]
  },
  "AirPalletLineDto": {},
  "UpsertNvoccBookingFormDto": {
    "service_scope": [
      "DOOR_TO_DOOR",
      "DOOR_TO_PORT",
      "PORT_TO_DOOR",
      "PORT_TO_PORT"
    ],
    "activity_sector": [
      "CIVILIAN",
      "MILITARY",
      "NUCLEAR"
    ]
  },
  "NvoccBookingFormPartyDto": {
    "party_kind": [
      "SHIPPER",
      "CONSIGNEE",
      "NOTIFY"
    ],
    "entity_kind": [
      "COMPANY",
      "INDIVIDUAL"
    ]
  },
  "UpdateSeaFclJobDetailDto": {
    "stuffing_location": [
      "CY",
      "CFS",
      "SHIPPER_PREMISES"
    ],
    "vgm_method": [
      "SM1",
      "SM2"
    ],
    "bl_type": [
      "Original",
      "Seaway",
      "Express Release",
      "Surrendered"
    ],
    "freight_terms": [
      "Prepaid",
      "Collect",
      "Third Party"
    ],
    "customs_status": [
      "PENDING",
      "FILED",
      "QUERY",
      "CLEARED",
      "RELEASED"
    ]
  },
  "UpdateLandJobDetailDto": {
    "vehicle_type": [
      "TRUCK",
      "TRAILER",
      "VAN"
    ],
    "freight_terms": [
      "Prepaid",
      "Collect",
      "Third Party"
    ]
  },
  "CreateQuotationDto": {
    "job_type": [
      "AIR_EXPORT",
      "AIR_IMPORT",
      "SEA_FCL_EXPORT",
      "SEA_FCL_IMPORT",
      "SEA_LCL_EXPORT",
      "SEA_LCL_IMPORT",
      "LAND",
      "ROAD_FREIGHT",
      "COURIER",
      "CUSTOMS_CLEARANCE",
      "NVOCC_EXPORT",
      "NVOCC_IMPORT",
      "SERVICE_JOB",
      "WAREHOUSE"
    ],
    "incoterm": [
      "EXW",
      "FCA",
      "FAS",
      "FOB",
      "CFR",
      "CIF",
      "CPT",
      "CIP",
      "DAP",
      "DPU",
      "DDP"
    ],
    "source": [
      "STAFF",
      "CUSTOMER_PORTAL",
      "ONLINE_WIDGET"
    ]
  },
  "UpdateQuotationDto": {
    "job_type": [
      "AIR_EXPORT",
      "AIR_IMPORT",
      "SEA_FCL_EXPORT",
      "SEA_FCL_IMPORT",
      "SEA_LCL_EXPORT",
      "SEA_LCL_IMPORT",
      "LAND",
      "ROAD_FREIGHT",
      "COURIER",
      "CUSTOMS_CLEARANCE",
      "NVOCC_EXPORT",
      "NVOCC_IMPORT",
      "SERVICE_JOB",
      "WAREHOUSE"
    ],
    "incoterm": [
      "EXW",
      "FCA",
      "FAS",
      "FOB",
      "CFR",
      "CIF",
      "CPT",
      "CIP",
      "DAP",
      "DPU",
      "DDP"
    ],
    "source": [
      "STAFF",
      "CUSTOMER_PORTAL",
      "ONLINE_WIDGET"
    ]
  },
  "CreateQuotationLineDto": {},
  "UpdateQuotationLineDto": {},
  "CargoPackageDto": {},
  "CreateOnlineQuoteDto": {
    "job_type": [
      "AIR_EXPORT",
      "AIR_IMPORT",
      "SEA_FCL_EXPORT",
      "SEA_FCL_IMPORT",
      "SEA_LCL_EXPORT",
      "SEA_LCL_IMPORT",
      "LAND",
      "ROAD_FREIGHT",
      "COURIER",
      "CUSTOMS_CLEARANCE",
      "NVOCC_EXPORT",
      "NVOCC_IMPORT",
      "SERVICE_JOB",
      "WAREHOUSE"
    ]
  },
  "PortalQuotationRequestDto": {
    "job_type": [
      "AIR_EXPORT",
      "AIR_IMPORT",
      "SEA_FCL_EXPORT",
      "SEA_FCL_IMPORT",
      "SEA_LCL_EXPORT",
      "SEA_LCL_IMPORT",
      "LAND",
      "ROAD_FREIGHT",
      "COURIER",
      "CUSTOMS_CLEARANCE",
      "NVOCC_EXPORT",
      "NVOCC_IMPORT",
      "SERVICE_JOB",
      "WAREHOUSE"
    ]
  },
  "PortalQuotationEstimateDto": {
    "job_type": [
      "AIR_EXPORT",
      "AIR_IMPORT",
      "SEA_FCL_EXPORT",
      "SEA_FCL_IMPORT",
      "SEA_LCL_EXPORT",
      "SEA_LCL_IMPORT",
      "LAND",
      "ROAD_FREIGHT",
      "COURIER",
      "CUSTOMS_CLEARANCE",
      "NVOCC_EXPORT",
      "NVOCC_IMPORT",
      "SERVICE_JOB",
      "WAREHOUSE"
    ]
  },
  "PortalCustomerLineDto": {
    "source": [
      "CATALOG",
      "TARIFF",
      "CUSTOMER_PROPOSED"
    ]
  },
  "PortalQuotationRejectDto": {
    "reason": [
      "Competitor Rate",
      "No Space",
      "Cargo Type",
      "No Longer Required",
      "Booked Elsewhere",
      "Price Too High",
      "Other"
    ]
  },
  "GenerateQuotationPdfDto": {
    "mode": [
      "CUSTOMER",
      "INTERNAL"
    ]
  }
} as const;

/** String length limits per DTO field (OpenAPI `maxLength`). */
export const API_MAX_LENGTH = {
  "UpsertSeaFclBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "pol": 100,
    "pod": 100,
    "incoterms": 10,
    "freight_terms": 30
  },
  "UpsertSeaLclBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "pol": 100,
    "pod": 100,
    "cfs_warehouse": 200,
    "incoterms": 10,
    "freight_terms": 30
  },
  "UpsertLandBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "origin_city_country": 200,
    "dest_city_country": 200,
    "vehicle_type": 50,
    "incoterms": 10
  },
  "UpsertRoadFreightBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "origin_city_country": 200,
    "dest_city_country": 200,
    "vehicle_type": 50,
    "incoterms": 10,
    "border_crossing": 200
  },
  "UpsertCourierBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "origin_city_country": 200,
    "dest_city_country": 200,
    "tracking_number": 100
  },
  "UpsertCustomsClearanceBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "border_or_port": 200,
    "entry_type": 20,
    "declaration_type": 50,
    "port_of_entry": 100,
    "port_of_exit": 100,
    "country_of_origin": 2,
    "country_of_destination": 2,
    "incoterms": 10,
    "invoice_currency": 3
  },
  "UpsertWarehouseBookingFormDto": {
    "client_booking_no": 50,
    "voyage_ref": 50,
    "commodity": 500,
    "hs_code": 20,
    "dg_class": 20,
    "warehouse_name": 200
  },
  "BookingFormPartyDto": {
    "full_name": 300,
    "city": 100,
    "country": 100
  },
  "ContainerSizeLineDto": {
    "iso_size": 30
  },
  "WhStockLineInputDto": {
    "sku_code": 40,
    "description": 500,
    "unit": 20
  },
  "CcCargoLineInputDto": {
    "description": 500,
    "hs_code": 12,
    "country_of_origin": 2,
    "unit": 20,
    "currency_code": 3
  },
  "UpsertAirBookingFormDto": {
    "commodity": 500,
    "flight_number": 20,
    "origin_airport_code": 10,
    "dest_airport_code": 10,
    "arrival_flight_number": 20,
    "mawb_from_origin": 50,
    "agent_at_origin": 200
  },
  "AirBookingFormPartyDto": {
    "full_name": 300,
    "city": 100,
    "country": 100
  },
  "UpsertAirComplianceBookingFormDto": {
    "voyage_ref": 50,
    "client_booking_no": 50,
    "origin_airport_code": 10,
    "dest_airport_code": 10,
    "commodity": 500,
    "hs_code": 20,
    "final_use": 200,
    "booking_agent_line": 100,
    "agent_requester_name": 200,
    "sq_bl_booking_reference": 200
  },
  "AirCompliancePartyDto": {
    "full_name": 300,
    "city": 100,
    "country": 100
  },
  "AirPalletLineDto": {
    "pallet_type": 30
  },
  "UpsertNvoccBookingFormDto": {
    "voyage_ref": 50,
    "client_booking_no": 50,
    "pol": 100,
    "pod": 100,
    "commodity": 500,
    "hs_code": 20,
    "final_use": 200,
    "booking_agent_line": 100,
    "agent_requester_name": 200,
    "sq_bl_booking_reference": 200
  },
  "NvoccBookingFormPartyDto": {
    "full_name": 300,
    "city": 100,
    "country": 100
  },
  "UpdateSeaFclJobDetailDto": {},
  "UpdateLandJobDetailDto": {
    "vehicle_number": 40,
    "driver_name": 200,
    "driver_license": 50,
    "origin_city_country": 200,
    "destination_city_country": 200,
    "incoterms": 10,
    "border_origin_country": 2,
    "border_destination_country": 2,
    "border_declaration_number": 100,
    "border_commodity": 500,
    "border_hs_code": 12
  },
  "CreateQuotationDto": {
    "hs_code": 12,
    "currency_code": 3
  },
  "UpdateQuotationDto": {
    "hs_code": 12,
    "currency_code": 3
  },
  "CreateQuotationLineDto": {
    "description": 300,
    "currency_code": 3
  },
  "UpdateQuotationLineDto": {
    "description": 300,
    "currency_code": 3
  },
  "CargoPackageDto": {},
  "CreateOnlineQuoteDto": {
    "tenant_slug": 100,
    "contact_name": 200,
    "currency_code": 3
  },
  "PortalQuotationRequestDto": {
    "currency_code": 3
  },
  "PortalQuotationEstimateDto": {
    "currency_code": 3
  },
  "PortalCustomerLineDto": {
    "code": 30,
    "description": 300,
    "unit": 50
  },
  "PortalQuotationRejectDto": {
    "notes": 500
  },
  "GenerateQuotationPdfDto": {
    "layout_variant": 50
  }
} as const;

/** Server-side defaults per DTO field (OpenAPI `default`). */
export const API_DEFAULTS = {
  "UpsertSeaFclBookingFormDto": {},
  "UpsertSeaLclBookingFormDto": {},
  "UpsertLandBookingFormDto": {},
  "UpsertRoadFreightBookingFormDto": {},
  "UpsertCourierBookingFormDto": {},
  "UpsertCustomsClearanceBookingFormDto": {
    "direction": "IMPORT"
  },
  "UpsertWarehouseBookingFormDto": {
    "bonded": false,
    "temperature_controlled": false
  },
  "BookingFormPartyDto": {},
  "ContainerSizeLineDto": {},
  "WhStockLineInputDto": {},
  "CcCargoLineInputDto": {},
  "UpsertAirBookingFormDto": {
    "is_dg": false,
    "mark_complete": true
  },
  "AirBookingFormPartyDto": {},
  "UpsertAirComplianceBookingFormDto": {},
  "AirCompliancePartyDto": {},
  "AirPalletLineDto": {},
  "UpsertNvoccBookingFormDto": {
    "shipper_owned_container": false,
    "is_dg": false,
    "attach_commercial_invoice": false,
    "attach_correspondence": false,
    "attach_cod_form": false,
    "attach_licence": false,
    "mark_complete": false
  },
  "NvoccBookingFormPartyDto": {},
  "UpdateSeaFclJobDetailDto": {},
  "UpdateLandJobDetailDto": {},
  "CreateQuotationDto": {
    "is_dg": false,
    "exchange_rate": 1
  },
  "UpdateQuotationDto": {
    "is_dg": false,
    "exchange_rate": 1
  },
  "CreateQuotationLineDto": {
    "quantity": 1,
    "exchange_rate": 1,
    "is_cost": false,
    "sort_order": 0
  },
  "UpdateQuotationLineDto": {
    "quantity": 1,
    "exchange_rate": 1,
    "is_cost": false,
    "sort_order": 0
  },
  "CargoPackageDto": {
    "pieces": 1
  },
  "CreateOnlineQuoteDto": {},
  "PortalQuotationRequestDto": {},
  "PortalQuotationEstimateDto": {},
  "PortalCustomerLineDto": {
    "quantity": 1,
    "source": "CUSTOMER_PROPOSED"
  },
  "PortalQuotationRejectDto": {},
  "GenerateQuotationPdfDto": {
    "mode": "CUSTOMER"
  }
} as const;

/** Required keys per DTO (OpenAPI `required`). */
export const API_REQUIRED = {
  "UpsertSeaFclBookingFormDto": [],
  "UpsertSeaLclBookingFormDto": [],
  "UpsertLandBookingFormDto": [],
  "UpsertRoadFreightBookingFormDto": [],
  "UpsertCourierBookingFormDto": [],
  "UpsertCustomsClearanceBookingFormDto": [],
  "UpsertWarehouseBookingFormDto": [],
  "BookingFormPartyDto": [
    "party_kind"
  ],
  "ContainerSizeLineDto": [
    "count"
  ],
  "WhStockLineInputDto": [],
  "CcCargoLineInputDto": [],
  "UpsertAirBookingFormDto": [],
  "AirBookingFormPartyDto": [
    "party_kind"
  ],
  "UpsertAirComplianceBookingFormDto": [],
  "AirCompliancePartyDto": [
    "party_kind"
  ],
  "AirPalletLineDto": [
    "pallet_type",
    "count"
  ],
  "UpsertNvoccBookingFormDto": [],
  "NvoccBookingFormPartyDto": [
    "party_kind"
  ],
  "UpdateSeaFclJobDetailDto": [],
  "UpdateLandJobDetailDto": [],
  "CreateQuotationDto": [
    "job_type",
    "customer_id",
    "currency_code"
  ],
  "UpdateQuotationDto": [],
  "CreateQuotationLineDto": [
    "charge_code_id",
    "description",
    "unit_price",
    "currency_code"
  ],
  "UpdateQuotationLineDto": [],
  "CargoPackageDto": [
    "gross_weight_kg"
  ],
  "CreateOnlineQuoteDto": [
    "tenant_slug",
    "job_type",
    "currency_code"
  ],
  "PortalQuotationRequestDto": [
    "job_type",
    "currency_code"
  ],
  "PortalQuotationEstimateDto": [
    "job_type",
    "currency_code"
  ],
  "PortalCustomerLineDto": [
    "unit_price"
  ],
  "PortalQuotationRejectDto": [
    "reason"
  ],
  "GenerateQuotationPdfDto": [
    "mode"
  ]
} as const;

/** Property keys per DTO (OpenAPI `properties`). */
export const API_SCHEMA_KEYS = {
  "UpsertSeaFclBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "pol",
    "pod",
    "shipper_owned_container",
    "teu_count",
    "containers",
    "etd",
    "eta",
    "incoterms",
    "freight_terms"
  ],
  "UpsertSeaLclBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "pol",
    "pod",
    "cfs_warehouse",
    "etd",
    "eta",
    "incoterms",
    "freight_terms"
  ],
  "UpsertLandBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "origin_city_country",
    "dest_city_country",
    "vehicle_type",
    "etd",
    "eta",
    "incoterms"
  ],
  "UpsertRoadFreightBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "origin_city_country",
    "dest_city_country",
    "vehicle_type",
    "etd",
    "eta",
    "incoterms",
    "border_crossing"
  ],
  "UpsertCourierBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "origin_city_country",
    "dest_city_country",
    "tracking_number",
    "etd",
    "eta"
  ],
  "UpsertCustomsClearanceBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "direction",
    "border_or_port",
    "entry_type",
    "declaration_type",
    "port_of_entry",
    "port_of_exit",
    "country_of_origin",
    "country_of_destination",
    "incoterms",
    "invoice_value_amount",
    "invoice_currency",
    "freight_job_id",
    "cargo_lines",
    "etd",
    "eta",
    "attach_coo",
    "attach_poa",
    "attach_permit"
  ],
  "UpsertWarehouseBookingFormDto": [
    "date_of_request",
    "client_booking_no",
    "voyage_ref",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "cargo_category",
    "is_dg",
    "dg_class",
    "gross_weight_kg",
    "net_weight_kg",
    "volume_cbm",
    "pieces",
    "insurance_details",
    "request_details",
    "attach_commercial_invoice",
    "attach_packing_list",
    "attach_bl_awb_copy",
    "attach_carnet",
    "attach_vehicle_title",
    "attach_msds",
    "attach_dangerous_goods_declaration",
    "attach_health_veterinary",
    "attach_fda_moh",
    "parties",
    "mark_complete",
    "consent_accepted",
    "warehouse_id",
    "warehouse_name",
    "expected_inbound_at",
    "expected_outbound_at",
    "storage_days_requested",
    "bonded",
    "temperature_controlled",
    "handling_instructions",
    "freight_job_id",
    "stock_lines"
  ],
  "BookingFormPartyDto": [
    "party_kind",
    "full_name",
    "address",
    "city",
    "country",
    "entity_kind",
    "other_details"
  ],
  "ContainerSizeLineDto": [
    "container_type_id",
    "iso_size",
    "count"
  ],
  "WhStockLineInputDto": [
    "sku_code",
    "description",
    "quantity",
    "unit",
    "cbm"
  ],
  "CcCargoLineInputDto": [
    "description",
    "hs_code",
    "country_of_origin",
    "quantity",
    "unit",
    "value_amount",
    "currency_code"
  ],
  "UpsertAirBookingFormDto": [
    "admin_override",
    "stage_override_reason",
    "pieces",
    "gross_weight_kg",
    "chargeable_weight_kg",
    "volume_cbm",
    "pallet_count",
    "pallets",
    "commodity",
    "special_handling",
    "notes",
    "is_dg",
    "flight_number",
    "flight_date",
    "origin_airport_code",
    "dest_airport_code",
    "arrival_flight_number",
    "mawb_from_origin",
    "agent_at_origin",
    "delivery_address",
    "customs_value",
    "parties",
    "mark_complete"
  ],
  "AirBookingFormPartyDto": [
    "party_kind",
    "full_name",
    "address",
    "city",
    "country",
    "entity_kind",
    "other_details"
  ],
  "UpsertAirComplianceBookingFormDto": [
    "date_of_request",
    "voyage_ref",
    "client_booking_no",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "origin_airport_code",
    "dest_airport_code",
    "pieces",
    "gross_weight_kg",
    "net_weight_kg",
    "chargeable_weight_kg",
    "volume_cbm",
    "pallet_count",
    "pallets",
    "is_dg",
    "commodity",
    "hs_code",
    "final_use",
    "activity_sector",
    "insurance_details",
    "lc_bank_details",
    "attach_commercial_invoice",
    "attach_correspondence",
    "attach_cod_form",
    "attach_licence",
    "booking_agent_line",
    "agent_requester_name",
    "sq_bl_booking_reference",
    "request_details",
    "parties",
    "mark_complete",
    "consent_accepted",
    "admin_override",
    "stage_override_reason"
  ],
  "AirCompliancePartyDto": [
    "party_kind",
    "full_name",
    "address",
    "city",
    "country",
    "entity_kind",
    "other_details"
  ],
  "AirPalletLineDto": [
    "pallet_type",
    "count",
    "length_cm",
    "width_cm",
    "height_cm",
    "weight_kg"
  ],
  "UpsertNvoccBookingFormDto": [
    "date_of_request",
    "voyage_ref",
    "client_booking_no",
    "gross_weight_kg",
    "net_weight_kg",
    "pol",
    "pod",
    "shipper_owned_container",
    "is_dg",
    "teu_count",
    "containers",
    "service_scope",
    "origin_door_address",
    "dest_door_address",
    "commodity",
    "hs_code",
    "final_use",
    "activity_sector",
    "insurance_details",
    "lc_bank_details",
    "attach_commercial_invoice",
    "attach_correspondence",
    "attach_cod_form",
    "attach_licence",
    "booking_agent_line",
    "agent_requester_name",
    "sq_bl_booking_reference",
    "request_details",
    "parties",
    "mark_complete",
    "consent_accepted",
    "admin_override",
    "stage_override_reason"
  ],
  "NvoccBookingFormPartyDto": [
    "party_kind",
    "full_name",
    "address",
    "city",
    "country",
    "entity_kind",
    "other_details"
  ],
  "UpdateSeaFclJobDetailDto": [
    "shipping_line_id",
    "vessel_id",
    "voyage_number",
    "hbl_number",
    "mbl_number",
    "booking_number",
    "carrier_booking_ref",
    "place_of_receipt",
    "place_of_delivery",
    "etd",
    "eta",
    "incoterms",
    "stuffing_location",
    "stuffing_date",
    "si_cutoff",
    "vgm_cutoff",
    "cy_cutoff",
    "si_submitted_at",
    "si_version",
    "vgm_submitted_at",
    "vgm_method",
    "port_of_loading_id",
    "port_of_discharge_id",
    "bl_type",
    "freight_terms",
    "transhipment_port",
    "sailed_at",
    "mbl_number_from_line",
    "hbl_number_from_agent",
    "actual_eta",
    "customs_entry_number",
    "customs_examination_details",
    "customs_duty_amount",
    "customs_tax_amount",
    "customs_clearance_date",
    "customs_status",
    "customs_broker_id",
    "linked_export_job_id",
    "cfs_storage_rate_per_day",
    "cfs_storage_start_date"
  ],
  "UpdateLandJobDetailDto": [
    "trucker_id",
    "vehicle_type",
    "vehicle_number",
    "driver_name",
    "driver_license",
    "origin_city_country",
    "destination_city_country",
    "etd",
    "eta",
    "incoterms",
    "freight_terms",
    "cross_border_docs_required",
    "border_origin_country",
    "border_destination_country",
    "border_declaration_number",
    "border_commodity",
    "border_hs_code",
    "border_declared_value"
  ],
  "CreateQuotationDto": [
    "company_id",
    "job_type",
    "customer_id",
    "salesperson_id",
    "branch_id",
    "department_id",
    "carrier_id",
    "origin_port_id",
    "dest_port_id",
    "incoterm",
    "commodity",
    "hs_code",
    "gross_weight",
    "chargeable_weight",
    "volume_cbm",
    "length_m",
    "width_m",
    "height_m",
    "packages",
    "pieces",
    "container_type_id",
    "container_count",
    "is_dg",
    "dg_class",
    "special_requirements",
    "carrier_preference",
    "transit_time_days",
    "routing_notes",
    "remarks",
    "internal_notes",
    "valid_until",
    "currency_code",
    "exchange_rate",
    "discount_percent",
    "discount_amount",
    "source"
  ],
  "UpdateQuotationDto": [
    "company_id",
    "job_type",
    "customer_id",
    "salesperson_id",
    "branch_id",
    "department_id",
    "carrier_id",
    "origin_port_id",
    "dest_port_id",
    "incoterm",
    "commodity",
    "hs_code",
    "gross_weight",
    "chargeable_weight",
    "volume_cbm",
    "length_m",
    "width_m",
    "height_m",
    "packages",
    "pieces",
    "container_type_id",
    "container_count",
    "is_dg",
    "dg_class",
    "special_requirements",
    "carrier_preference",
    "transit_time_days",
    "routing_notes",
    "remarks",
    "internal_notes",
    "valid_until",
    "currency_code",
    "exchange_rate",
    "discount_percent",
    "discount_amount",
    "source"
  ],
  "CreateQuotationLineDto": [
    "charge_code_id",
    "description",
    "unit",
    "quantity",
    "unit_price",
    "currency_code",
    "exchange_rate",
    "tax_rate_id",
    "is_cost",
    "supplier_id",
    "sort_order"
  ],
  "UpdateQuotationLineDto": [
    "charge_code_id",
    "description",
    "unit",
    "quantity",
    "unit_price",
    "currency_code",
    "exchange_rate",
    "tax_rate_id",
    "is_cost",
    "supplier_id",
    "sort_order"
  ],
  "CargoPackageDto": [
    "length_m",
    "width_m",
    "height_m",
    "length_cm",
    "width_cm",
    "height_cm",
    "gross_weight_kg",
    "pieces"
  ],
  "CreateOnlineQuoteDto": [
    "tenant_slug",
    "job_type",
    "customer_id",
    "company_id",
    "contact_email",
    "contact_name",
    "origin_port_id",
    "dest_port_id",
    "commodity",
    "gross_weight",
    "chargeable_weight",
    "volume_cbm",
    "pieces",
    "container_type_id",
    "special_requirements",
    "valid_until",
    "currency_code"
  ],
  "PortalQuotationRequestDto": [
    "job_type",
    "origin_port_id",
    "dest_port_id",
    "commodity",
    "gross_weight",
    "chargeable_weight",
    "volume_cbm",
    "pieces",
    "container_type_id",
    "special_requirements",
    "valid_until",
    "container_count",
    "currency_code",
    "packages",
    "service_codes",
    "customer_lines",
    "estimate_snapshot"
  ],
  "PortalQuotationEstimateDto": [
    "job_type",
    "origin_port_id",
    "dest_port_id",
    "commodity",
    "gross_weight",
    "chargeable_weight",
    "volume_cbm",
    "pieces",
    "container_type_id",
    "special_requirements",
    "valid_until",
    "container_count",
    "currency_code",
    "packages",
    "service_codes",
    "customer_lines",
    "estimate_snapshot"
  ],
  "PortalCustomerLineDto": [
    "charge_code_id",
    "code",
    "description",
    "quantity",
    "unit_price",
    "unit",
    "source"
  ],
  "PortalQuotationRejectDto": [
    "reason",
    "notes"
  ],
  "GenerateQuotationPdfDto": [
    "mode",
    "layout_variant"
  ]
} as const;
