export const QUOTATION_API = {
  list: '/quotations',
  create: '/quotations',
  onlineQuote: '/quotations/online-quote',
  expireDue: '/quotations/expire-due',
  byId: (id: string) => `/quotations/${id}`,
  revisions: (id: string) => `/quotations/${id}/revisions`,
  lines: (id: string) => `/quotations/${id}/lines`,
  lineById: (id: string, lineId: string) => `/quotations/${id}/lines/${lineId}`,
  applyTariff: (id: string) => `/quotations/${id}/apply-tariff`,
  submit: (id: string) => `/quotations/${id}/submit`,
  approve: (id: string) => `/quotations/${id}/approve`,
  reject: (id: string) => `/quotations/${id}/reject`,
  send: (id: string) => `/quotations/${id}/send`,
  markWon: (id: string) => `/quotations/${id}/mark-won`,
  markLost: (id: string) => `/quotations/${id}/mark-lost`,
  duplicate: (id: string) => `/quotations/${id}/duplicate`,
  convertToJob: (id: string) => `/quotations/${id}/convert-to-job`,
  archive: (id: string) => `/quotations/${id}/archive`,
  expire: (id: string) => `/quotations/${id}/expire`,
  pdf: (id: string) => `/quotations/${id}/pdf`,
  pdfStatus: (id: string) => `/quotations/${id}/pdf/status`,
  sendEmail: (id: string) => `/quotations/${id}/send-email`,
  tariffs: '/quotations/tariffs',
  tariffById: (id: string) => `/quotations/tariffs/${id}`,
  zipDistances: '/quotations/zip-distances',
  zipDistanceById: (id: string) => `/quotations/zip-distances/${id}`,
  reports: {
    chargewise: '/quotations/reports/chargewise',
    analytics: '/quotations/reports/analytics',
    conversion: '/quotations/reports/analytics/conversion',
    lostReasons: '/quotations/reports/analytics/lost-reasons',
    responseTime: '/quotations/reports/analytics/response-time',
  },
} as const;
