export const QUOTATION_API = {
  list: '/quotations',
  create: '/quotations',
  onlineQuote: '/quotations/online-quote',
  expireDue: '/quotations/expire-due',
  dashboardStats: '/quotations/dashboard-stats',
  byId: (id: string) => `/quotations/${id}`,
  /** Fresa quotation detail — header, sections, actions, links. */
  detail: (id: string) => `/quotations/${id}/detail`,
  detailTab: (id: string, tab: string) =>
    `/quotations/${id}/detail/${encodeURIComponent(tab)}`,
  changeStatus: (id: string) => `/quotations/${id}/change-status`,
  copy: (id: string) => `/quotations/${id}/copy`,
  revisions: (id: string) => `/quotations/${id}/revisions`,
  lines: (id: string) => `/quotations/${id}/lines`,
  lineById: (id: string, lineId: string) => `/quotations/${id}/lines/${lineId}`,
  applyTariff: (id: string) => `/quotations/${id}/apply-tariff`,
  submit: (id: string) => `/quotations/${id}/submit`,
  approve: (id: string) => `/quotations/${id}/approve`,
  /** Fresa continuum: verify quotation before approve-verified. */
  verify: (id: string) => `/quotations/${id}/verify`,
  /** Fresa continuum: approve a verified quotation. */
  approveVerified: (id: string) => `/quotations/${id}/approve-verified`,
  reject: (id: string) => `/quotations/${id}/reject`,
  send: (id: string) => `/quotations/${id}/send`,
  markWon: (id: string) => `/quotations/${id}/mark-won`,
  markLost: (id: string) => `/quotations/${id}/mark-lost`,
  duplicate: (id: string) => `/quotations/${id}/duplicate`,
  convertToJob: (id: string) => `/quotations/${id}/convert-to-job`,
  generateShipment: (id: string) => `/quotations/${id}/generate-shipment`,
  generateJob: (id: string) => `/quotations/${id}/generate-job`,
  archive: (id: string) => `/quotations/${id}/archive`,
  expire: (id: string) => `/quotations/${id}/expire`,
  pdf: (id: string) => `/quotations/${id}/pdf`,
  sendToVendor: (id: string) => `/quotations/${id}/send-to-vendor`,
  passToVendor: (id: string) => `/quotations/${id}/pass-to-vendor`,
  jobOffers: (id: string) => `/quotations/${id}/job-offers`,
  pdfStatus: (id: string) => `/quotations/${id}/pdf/status`,
  sendEmail: (id: string) => `/quotations/${id}/send-email`,
  tariffs: '/quotations/tariffs',
  tariffById: (id: string) => `/quotations/tariffs/${id}`,
  zipDistances: '/quotations/zip-distances',
  zipDistanceById: (id: string) => `/quotations/zip-distances/${id}`,
  reports: {
    chargewise: '/quotations/reports/chargewise',
    analytics: '/quotations/reports/analytics',
    conversion: '/quotations/reports/analytics/conversion',
    lostReasons: '/quotations/reports/analytics/lost-reasons',
    responseTime: '/quotations/reports/analytics/response-time',
  },
  serviceCatalog: {
    list: '/quotations/service-catalog',
    byId: (id: string) => `/quotations/service-catalog/${id}`,
  },
  reviseAndSend: (id: string) => `/quotations/${id}/revise-and-send`,
  negotiation: (id: string) => `/quotations/${id}/negotiation`,
  negotiationAccept: (id: string) => `/quotations/${id}/negotiation/accept`,
  negotiationReject: (id: string) => `/quotations/${id}/negotiation/reject`,
} as const;
