export const CUSTOMS_CLEARANCE_API = {
  dashboard: '/jobs/cc/dashboard',
  queue: '/jobs/cc/queue',
  details: (id: string) => `/jobs/${id}/cc/details`,
  open: (id: string) => `/jobs/${id}/cc/open`,
  status: (id: string) => `/jobs/${id}/cc/status`,
  lines: (id: string) => `/jobs/${id}/cc/lines`,
  lineById: (id: string, lineId: string) => `/jobs/${id}/cc/lines/${lineId}`,
  classifyLine: (id: string, lineId: string) => `/jobs/${id}/cc/lines/${lineId}/classify`,
  checklist: (id: string) => `/jobs/${id}/cc/checklist`,
  checklistItem: (id: string, itemId: string) => `/jobs/${id}/cc/checklist/${itemId}`,
  checklistSeed: (id: string) => `/jobs/${id}/cc/checklist/seed`,
  stageDocsComplete: (id: string) => `/jobs/${id}/cc/stage/docs-complete`,
  stageClassify: (id: string) => `/jobs/${id}/cc/stage/classify`,
  stageFile: (id: string) => `/jobs/${id}/cc/stage/file`,
  filing: (id: string) => `/jobs/${id}/cc/filing`,
  stageAssess: (id: string) => `/jobs/${id}/cc/stage/assess`,
  queries: (id: string) => `/jobs/${id}/cc/queries`,
  queryById: (id: string, queryId: string) => `/jobs/${id}/cc/queries/${queryId}`,
  queryClose: (id: string, queryId: string) => `/jobs/${id}/cc/queries/${queryId}/close`,
  dutyPaymentRequest: (id: string) => `/jobs/${id}/cc/duty-payment-request`,
  stageDutyPaid: (id: string) => `/jobs/${id}/cc/stage/duty-paid`,
  stageClear: (id: string) => `/jobs/${id}/cc/stage/clear`,
  stageRelease: (id: string) => `/jobs/${id}/cc/stage/release`,
  stageInvoiceReady: (id: string) => `/jobs/${id}/cc/stage/invoice-ready`,
  stageClose: (id: string) => `/jobs/${id}/cc/stage/close`,
  financialSummary: (id: string) => `/jobs/${id}/cc/financial-summary`,
  linkFreight: (id: string) => `/jobs/${id}/cc/link-freight`,
  declaration: (id: string) => `/jobs/${id}/cc/declaration`,
  declarationValidate: (id: string) => `/jobs/${id}/cc/declaration/validate`,
  declarationSubmitLocal: (id: string) => `/jobs/${id}/cc/declaration/submit-local`,
  entryPack: (id: string) => `/jobs/${id}/cc/documents/entry-pack`,
  hsValidate: '/masters/hs-codes/validate',
} as const;

export const PORTAL_CC_API = {
  list: '/portal/cc-jobs',
  byId: (id: string) => `/portal/cc-jobs/${encodeURIComponent(id)}`,
  checklist: (id: string) => `/portal/cc-jobs/${encodeURIComponent(id)}/checklist`,
  documents: (id: string) => `/portal/cc-jobs/${encodeURIComponent(id)}/documents`,
} as const;
