import {
  Phone,
  ArrowRight,
  ThumbsUp,
  DollarSign,
  Wallet,
  Gauge,
  ListChecks,
  IdCard,
  FileText,
  CalendarCheck,
  ClipboardList,
  Mail,
} from 'lucide-react';
import type { MenuTile } from '../../customers/types/menu.types';

export const salesMenu: MenuTile[] = [
  {
    id: 'call-sheet',
    title: 'Call Sheet',
    description: 'Log sales calls, visits, outcomes, and review daily salesperson activity.',
    icon: Phone,
    iconColor: 'bg-sky-500',
    path: '/sales/call-sheet',
  },
  {
    id: 'client-request-list',
    title: 'Client Request List',
    description: 'To view the organization list which created by the current user.',
    icon: ArrowRight,
    iconColor: 'bg-sky-500',
    path: '/sales/client-request-list',
  },
  {
    id: 'lead',
    title: 'Lead',
    description: 'Capture prospects, manage the sales pipeline, and convert qualified leads to parties.',
    icon: ThumbsUp,
    iconColor: 'bg-emerald-500',
    path: '/sales/lead',
  },
  {
    id: 'follow-ups',
    title: 'Follow-ups',
    description: 'Plan pending actions, manage due dates, and close completed sales tasks.',
    icon: CalendarCheck,
    iconColor: 'bg-violet-500',
    path: '/sales/follow-ups',
  },
  {
    id: 'enquiries',
    title: 'Enquiries',
    description: 'Record freight requirements and convert qualified enquiries into quotations.',
    icon: ClipboardList,
    iconColor: 'bg-indigo-500',
    path: '/sales/enquiries',
  },
  {
    id: 'rate-charges',
    title: 'Rate Charges',
    description: 'To maintain rate charges details such as owner, carrier, client, port details, currency rate and min / max currency rates.',
    icon: DollarSign,
    iconColor: 'bg-emerald-500',
    path: '/sales/rate-charges',
  },
  {
    id: 'sales-budget',
    title: 'Sales Budget',
    description: 'Set salesperson targets by period and service, and compare performance.',
    icon: Wallet,
    iconColor: 'bg-lime-500',
    path: '/sales/sales-budget',
  },
  {
    id: 'sales-dashboard',
    title: 'Sales Dashboard',
    description: 'Review CRM KPIs, pipeline performance, conversion, and sales reports.',
    icon: Gauge,
    iconColor: 'bg-yellow-500',
    path: '/sales/sales-dashboard',
  },
  {
    id: 'email-marketing',
    title: 'Email Marketing',
    description: 'Manage subscribers, reusable templates, and outbound sales campaigns.',
    icon: Mail,
    iconColor: 'bg-rose-500',
    path: '/sales/email-marketing',
  },
  {
    id: 'shipments-list-sales',
    title: 'Shipments List-Sales',
    description: 'The list of users can view based on mapped Employee users list.',
    icon: ListChecks,
    iconColor: 'bg-amber-500',
    path: '/sales/shipments-list',
  },
  {
    id: 'visiting-card-list-report',
    title: 'Visiting Card List Report',
    description: 'The Visiting Card Scanner enables users to scan business card images using AI-based data extraction. The extracted contact information is automatically captured and saved against the',
    icon: IdCard,
    iconColor: 'bg-orange-600',
    path: '/sales/visiting-card-list',
  },
];

// Rendered separately with a distinct centered layout, same pattern as Reports - Quotation
export const reportsSalesTile: MenuTile = {
  id: 'reports-sales',
  title: 'Reports - Sales',
  description: 'Pipeline, win/loss, budget vs actual, enquiry conversion, overdue follow-ups, and other CRM sales reports.',
  icon: FileText,
  iconColor: 'bg-sky-500',
  path: '/sales/sales-dashboard',
};