import type { MasterResourceConfig } from '../types/master.types';
import { MASTER_PATHS, type MasterResourceKey } from '../api/masterPaths';
import { CONTAINER_TYPE_SIZE_OPTIONS } from '../constants/containerTypeSizes';

const boolActive = {
  name: 'is_active',
  label: 'Active',
  type: 'boolean' as const,
};

const countryCodeField = {
  name: 'country_code',
  label: 'Country code',
  type: 'text' as const,
  placeholder: 'AE',
};

/** All Swagger-backed master resources. */
export const MASTER_RESOURCES: Record<MasterResourceKey, MasterResourceConfig> = {
  airlines: {
    key: 'airlines',
    title: 'Airlines',
    basePath: MASTER_PATHS.airlines,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'iata_code', label: 'IATA', mono: true },
      { key: 'icao_code', label: 'ICAO', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'iata_code', label: 'IATA code', type: 'text', required: true, mono: true, placeholder: 'EK' },
      { name: 'icao_code', label: 'ICAO code', type: 'text', mono: true, placeholder: 'UAE' },
      { name: 'prefix_code', label: 'AWB prefix', type: 'text', placeholder: '176', mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      countryCodeField,
      boolActive,
    ],
  },
  airports: {
    key: 'airports',
    title: 'Airports',
    basePath: MASTER_PATHS.airports,
    labelField: 'name',
    supportsDelete: true,
    /** World catalog — show exact seeded fields. */
    columns: [
      { key: 'iata_code', label: 'IATA', mono: true },
      { key: 'icao_code', label: 'ICAO', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'timezone', label: 'Timezone' },
    ],
    fields: [
      { name: 'iata_code', label: 'IATA code', type: 'text', required: true, mono: true },
      { name: 'icao_code', label: 'ICAO code', type: 'text', mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text' },
      { ...countryCodeField, required: true },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Dubai' },
      boolActive,
    ],
  },
  banks: {
    key: 'banks',
    title: 'Banks',
    basePath: MASTER_PATHS.banks,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'short_name', label: 'Short name' },
      { key: 'swift_code', label: 'SWIFT', mono: true },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'short_name', label: 'Short name', type: 'text' },
      { name: 'swift_code', label: 'SWIFT / BIC', type: 'text', mono: true, placeholder: 'BOMLAEAD' },
      { name: 'iban_prefix', label: 'IBAN prefix', type: 'text' },
      countryCodeField,
      boolActive,
    ],
  },
  branches: {
    key: 'branches',
    title: 'Branches',
    basePath: MASTER_PATHS.branches,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        required: true,
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'name',
        label: 'Branch name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Dubai Head Office',
      },
      {
        name: 'code',
        label: 'Branch code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'e.g. KF-DHO',
      },
      { name: 'address', label: 'Address', type: 'textarea' },
      {
        name: 'city',
        label: 'City',
        type: 'text',
        required: true,
        placeholder: 'Dubai',
      },
      {
        name: 'country_code',
        label: 'Country',
        type: 'text',
        required: true,
        placeholder: 'AE',
      },
      {
        name: 'phone',
        label: 'Phone',
        type: 'text',
        required: true,
        placeholder: '+971501234567',
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'branch@company.com',
      },
      { name: 'is_head_office', label: 'Head office', type: 'boolean' },
      boolActive,
    ],
  },
  'charge-codes': {
    key: 'charge-codes',
    title: 'Charge Codes',
    basePath: MASTER_PATHS['charge-codes'],
    labelField: 'code',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'description', label: 'Description' },
      { key: 'charge_group', label: 'Group' },
      { key: 'unit', label: 'Unit' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'description', label: 'Description', type: 'text', required: true },
      {
        name: 'charge_group',
        label: 'Charge group',
        type: 'select',
        options: [
          { value: 'FREIGHT', label: 'Freight' },
          { value: 'LOCAL_CHARGES', label: 'Local charges' },
          { value: 'CUSTOMS', label: 'Customs' },
          { value: 'DOCUMENTATION', label: 'Documentation' },
          { value: 'HANDLING', label: 'Handling' },
          { value: 'STORAGE', label: 'Storage' },
          { value: 'DEMURRAGE', label: 'Demurrage' },
          { value: 'DETENTION', label: 'Detention' },
          { value: 'INSURANCE', label: 'Insurance' },
          { value: 'ORIGIN_CHARGES', label: 'Origin charges' },
          { value: 'DESTINATION_CHARGES', label: 'Destination charges' },
          { value: 'SURCHARGES', label: 'Surcharges' },
          { value: 'OTHER', label: 'Other' },
        ],
      },
      {
        name: 'applicable_modes',
        label: 'Applicable modes',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'AIR', label: 'Air' },
          { value: 'SEA', label: 'Sea' },
          { value: 'LAND', label: 'Land' },
          { value: 'COURIER', label: 'Courier' },
        ],
      },
      { name: 'tax_applicable', label: 'Tax applicable', type: 'boolean' },
      {
        name: 'tax_rate_id',
        label: 'Tax rate',
        type: 'select',
        optionsFrom: 'tax-rates',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
        placeholder: 'Optional — create Tax Rates first',
      },
      { name: 'gl_revenue_code', label: 'GL revenue code', type: 'text' },
      { name: 'gl_cost_code', label: 'GL cost code', type: 'text' },
      {
        name: 'unit',
        label: 'Unit of measure',
        type: 'select',
        optionsFrom: 'units-of-measure',
        optionsValueKey: 'code',
        optionsLabelKey: 'name',
        placeholder: 'Select UOM from master data',
      },
      { name: 'is_mandatory', label: 'Mandatory', type: 'boolean' },
      boolActive,
    ],
  },
  'container-types': {
    key: 'container-types',
    title: 'Container Types',
    basePath: MASTER_PATHS['container-types'],
    labelField: 'name',
    supportsDelete: true,
    supportsSeedDefaults: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'size', label: 'Size / unit', mono: true },
      { key: 'teu', label: 'TEU' },
    ],
    fields: [
      {
        name: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: '40HC',
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: "40ft High Cube",
      },
      {
        name: 'size',
        label: 'Size / unit',
        type: 'select',
        required: true,
        options: CONTAINER_TYPE_SIZE_OPTIONS.map(({ value, label }) => ({ value, label })),
      },
      { name: 'teu', label: 'TEU', type: 'number', placeholder: '2' },
      { name: 'max_payload', label: 'Max payload (kg)', type: 'number', placeholder: '26500' },
      { name: 'volume_cbm', label: 'Volume (CBM)', type: 'number', placeholder: '76.3' },
      boolActive,
    ],
  },
  'air-pallet-types': {
    key: 'air-pallet-types',
    title: 'Air Pallet Types',
    basePath: MASTER_PATHS['air-pallet-types'],
    labelField: 'name',
    supportsDelete: true,
    supportsSeedDefaults: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'iata_codes', label: 'IATA codes', mono: true },
      { key: 'usable_volume_m3', label: 'Usable m³' },
      { key: 'height_m', label: 'Height (m)' },
    ],
    fields: [
      {
        name: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'LD3',
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'LD3 Container',
      },
      {
        name: 'iata_codes',
        label: 'IATA codes (CSV)',
        type: 'text',
        csvToArray: true,
        mono: true,
        placeholder: 'AKE, AVE',
      },
      { name: 'base_length_m', label: 'Base length (m)', type: 'number', placeholder: '1.56' },
      { name: 'base_width_m', label: 'Base width (m)', type: 'number', placeholder: '1.53' },
      { name: 'height_m', label: 'Height (m)', type: 'number', placeholder: '1.63' },
      {
        name: 'usable_volume_m3',
        label: 'Usable volume (m³)',
        type: 'number',
        placeholder: '4.5',
      },
      { name: 'inside_length_m', label: 'Inside length (m)', type: 'number' },
      { name: 'inside_width_m', label: 'Inside width (m)', type: 'number' },
      { name: 'inside_height_m', label: 'Inside height (m)', type: 'number' },
      {
        name: 'aircraft_types',
        label: 'Aircraft types (CSV)',
        type: 'text',
        csvToArray: true,
        placeholder: 'A300, A330, B747-400',
      },
      boolActive,
    ],
  },
  'courier-vendors': {
    key: 'courier-vendors',
    title: 'Courier Vendors',
    basePath: MASTER_PATHS['courier-vendors'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'DHL Express' },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'DHL' },
      countryCodeField,
      { name: 'phone', label: 'Phone', type: 'text', placeholder: '+971501234567' },
      { name: 'email', label: 'Email', type: 'text', placeholder: 'ops@courier.example' },
      {
        name: 'tracking_url_template',
        label: 'Tracking URL template',
        type: 'text',
        placeholder: 'https://…/{trackingNumber}',
      },
      boolActive,
    ],
  },
  countries: {
    key: 'countries',
    title: 'Countries',
    basePath: MASTER_PATHS.countries,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'iso_code', label: 'ISO', mono: true },
      { key: 'iso3_code', label: 'ISO3', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'dial_code', label: 'Dial' },
      { key: 'region', label: 'Region' },
    ],
    fields: [
      { name: 'iso_code', label: 'ISO code', type: 'text', required: true, mono: true },
      { name: 'iso3_code', label: 'ISO3 code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'dial_code', label: 'Dial code', type: 'select', placeholder: 'Select dial code…', mono: true },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'Middle East' },
      boolActive,
    ],
  },
  currencies: {
    key: 'currencies',
    title: 'Currencies',
    basePath: MASTER_PATHS.currencies,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'symbol', label: 'Symbol' },
      { key: 'decimal_places', label: 'Decimals' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'symbol', label: 'Symbol', type: 'text', required: true },
      { name: 'decimal_places', label: 'Decimal places', type: 'number' },
      { name: 'is_base', label: 'Base currency', type: 'boolean' },
      boolActive,
    ],
  },
  departments: {
    key: 'departments',
    title: 'Departments',
    basePath: MASTER_PATHS.departments,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        required: true,
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'name', label: 'Department name', type: 'text', required: true, placeholder: 'Select or type a department name…' },
      {
        name: 'code',
        label: 'Department code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'e.g. KF-HR (max 20 chars)',
      },
      {
        name: 'parent_id',
        label: 'Parent department',
        type: 'select',
        optionsFrom: 'departments',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
        placeholder: 'Type to search or select parent department…',
      },
      boolActive,
    ],
  },
  designations: {
    key: 'designations',
    title: 'Designations',
    basePath: MASTER_PATHS.designations,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'department_id', label: 'Department', mono: true },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'name',
        label: 'Designation name',
        type: 'text',
        required: true,
        placeholder: 'Select or type a designation…',
      },
      {
        name: 'department_id',
        label: 'Department',
        type: 'select',
        optionsFrom: 'departments',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
        placeholder: 'Type to search or select a department…',
      },
      boolActive,
    ],
  },
  'exchange-rates': {
    key: 'exchange-rates',
    title: 'Exchange Rates',
    basePath: MASTER_PATHS['exchange-rates'],
    labelField: 'rate',
    supportsDelete: false,
    createOnly: true,
    columns: [
      { key: 'currency_id', label: 'Currency', mono: true },
      { key: 'base_currency', label: 'Base', mono: true },
      { key: 'rate', label: 'Rate' },
      { key: 'rate_date', label: 'Date' },
      { key: 'source', label: 'Source' },
    ],
    fields: [
      {
        name: 'currency_id',
        label: 'Currency',
        type: 'select',
        required: true,
        optionsFrom: 'currencies',
        optionsValueKey: 'id',
        optionsLabelKey: 'code',
        placeholder: 'Select currency to rate…',
      },
      {
        name: 'base_currency',
        label: 'Base currency',
        type: 'select',
        required: true,
        optionsFrom: 'currencies',
        optionsValueKey: 'code',
        optionsLabelKey: 'code',
        placeholder: 'Select base currency…',
      },
      {
        name: 'rate',
        label: 'Rate',
        type: 'number',
        required: true,
        placeholder: 'Auto-fetched when currencies are selected',
      },
      { name: 'rate_date', label: 'Rate date', type: 'date', required: true },
      {
        name: 'source',
        label: 'Source',
        type: 'text',
        placeholder: 'Filled automatically from market feed',
      },
    ],
  },
  holidays: {
    key: 'holidays',
    title: 'Holidays',
    basePath: MASTER_PATHS.holidays,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'date', label: 'Date' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'is_recurring', label: 'Recurring' },
    ],
    fields: [
      {
        name: 'country_code',
        label: 'Country',
        type: 'select',
        required: true,
        optionsFrom: 'countries',
        optionsValueKey: 'iso_code',
        optionsLabelKey: 'name',
        placeholder: 'Select country (create under Countries first)',
      },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'UAE National Day' },
      { name: 'is_recurring', label: 'Recurring yearly', type: 'boolean' },
    ],
  },
  'hs-codes': {
    key: 'hs-codes',
    title: 'HS Codes',
    basePath: MASTER_PATHS['hs-codes'],
    labelField: 'hs_code',
    supportsDelete: true,
    columns: [
      { key: 'hs_code', label: 'HS Code', mono: true },
      { key: 'description', label: 'Description' },
      { key: 'dg_class', label: 'DG class' },
    ],
    fields: [
      {
        name: 'hs_code',
        label: 'HS code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: '8517.12',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Commodity description for customs',
      },
      {
        name: 'import_duty_rate',
        label: 'Import duty rate (%)',
        type: 'number',
        placeholder: '0–100',
      },
      {
        name: 'export_duty_rate',
        label: 'Export duty rate (%)',
        type: 'number',
        placeholder: '0–100',
      },
      {
        name: 'dg_class',
        label: 'DG class',
        type: 'text',
        placeholder: 'e.g. 3 or 2.1',
      },
      {
        name: 'un_number',
        label: 'UN number',
        type: 'text',
        placeholder: 'UN1203',
        mono: true,
      },
      { name: 'is_prohibited', label: 'Prohibited', type: 'boolean' },
      { name: 'is_restricted', label: 'Restricted', type: 'boolean' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
      boolActive,
    ],
  },
  ports: {
    key: 'ports',
    title: 'Ports',
    basePath: MASTER_PATHS.ports,
    labelField: 'name',
    supportsDelete: true,
    /** World catalog — show exact seeded fields. */
    columns: [
      { key: 'un_locode', label: 'UNLOCODE', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'mode', label: 'Mode' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      {
        name: 'un_locode',
        label: 'UNLOCODE',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'AEJEA',
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Jebel Ali',
      },
      { name: 'city', label: 'City', type: 'text', placeholder: 'e.g. Dubai' },
      { ...countryCodeField, required: true },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        required: true,
        options: [
          { value: 'SEA', label: 'Sea' },
          { value: 'AIR', label: 'Air' },
          { value: 'LAND', label: 'Land' },
          { value: 'COURIER', label: 'Courier' },
        ],
      },
      { name: 'latitude', label: 'Latitude', type: 'number', placeholder: '-90 to 90' },
      { name: 'longitude', label: 'Longitude', type: 'number', placeholder: '-180 to 180' },
      boolActive,
    ],
  },
  'shipping-lines': {
    key: 'shipping-lines',
    title: 'Shipping Lines',
    basePath: MASTER_PATHS['shipping-lines'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'scac_code', label: 'SCAC', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'short_name', label: 'Short name' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'scac_code', label: 'SCAC code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'short_name', label: 'Short name', type: 'text' },
      countryCodeField,
      { name: 'website', label: 'Website', type: 'url' },
      { name: 'tracking_url', label: 'Tracking URL', type: 'url' },
      boolActive,
    ],
  },
  'tax-rates': {
    key: 'tax-rates',
    title: 'Tax Rates',
    basePath: MASTER_PATHS['tax-rates'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'rate', label: 'Rate' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'UAE VAT Standard' },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'VAT5' },
      {
        name: 'tax_type',
        label: 'Tax type',
        type: 'select',
        options: [
          { value: 'VAT', label: 'VAT' },
          { value: 'GST', label: 'GST' },
          { value: 'CUSTOMS', label: 'Customs' },
          { value: 'WITHHOLDING', label: 'Withholding' },
          { value: 'NONE', label: 'None' },
        ],
      },
      { name: 'rate', label: 'Rate (%)', type: 'number', required: true, placeholder: '5' },
      {
        name: 'country_code',
        label: 'Country',
        type: 'select',
        required: true,
        optionsFrom: 'countries',
        optionsValueKey: 'iso_code',
        optionsLabelKey: 'name',
      },
      { name: 'effective_from', label: 'Effective from', type: 'date', required: true },
      { name: 'effective_to', label: 'Effective to', type: 'date' },
      { name: 'is_default', label: 'Default', type: 'boolean' },
      boolActive,
    ],
  },
  truckers: {
    key: 'truckers',
    title: 'Truckers',
    basePath: MASTER_PATHS.truckers,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      countryCodeField,
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'contact_person', label: 'Contact person', type: 'text' },
      boolActive,
    ],
  },
  'units-of-measure': {
    key: 'units-of-measure',
    title: 'Units of Measure',
    basePath: MASTER_PATHS['units-of-measure'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
    ],
    fields: [
      {
        name: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'e.g. CBM',
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Cubic Meter',
      },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        options: [
          { value: 'Weight', label: 'Weight' },
          { value: 'Volume', label: 'Volume' },
          { value: 'Length', label: 'Length' },
          { value: 'Count', label: 'Count' },
          { value: 'Area', label: 'Area' },
          { value: 'Time', label: 'Time' },
          { value: 'Temperature', label: 'Temperature' },
          { value: 'Package', label: 'Package' },
          { value: 'Other', label: 'Other' },
        ],
        placeholder: 'Pick a category or type your own…',
      },
      boolActive,
    ],
  },
  vessels: {
    key: 'vessels',
    title: 'Vessels',
    basePath: MASTER_PATHS.vessels,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'imo_number', label: 'IMO', mono: true },
      { key: 'flag_country', label: 'Flag' },
      { key: 'vessel_type', label: 'Type' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'imo_number', label: 'IMO number', type: 'text', mono: true, placeholder: '9123456' },
      { name: 'flag_country', label: 'Flag country', type: 'text' },
      {
        name: 'shipping_line_id',
        label: 'Shipping line',
        type: 'select',
        optionsFrom: 'shipping-lines',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'vessel_type', label: 'Vessel type', type: 'text' },
      { name: 'year_built', label: 'Year built', type: 'number' },
      { name: 'gross_tonnage', label: 'Gross tonnage', type: 'number' },
      boolActive,
    ],
  },
  warehouses: {
    key: 'warehouses',
    title: 'Warehouses',
    basePath: MASTER_PATHS.warehouses,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. Jebel Ali Warehouse 3',
      },
      {
        name: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        mono: true,
        placeholder: 'e.g. WH-JA3',
      },
      {
        name: 'address',
        label: 'Address',
        type: 'textarea',
        placeholder: 'Street / facility address',
      },
      { name: 'city', label: 'City', type: 'text', placeholder: 'e.g. Dubai' },
      countryCodeField,
      {
        name: 'capacity_sqm',
        label: 'Capacity (sqm)',
        type: 'number',
        placeholder: '0 or greater',
      },
      boolActive,
    ],
  },
  tariffs: {
    key: 'tariffs',
    title: 'Online Tariff Master',
    basePath: MASTER_PATHS.tariffs,
    labelField: 'service_type',
    supportsDelete: true,
    menuPath: '/quotations/tariff-master',
    columns: [
      { key: 'service_type', label: 'Service' },
      { key: 'currency_code', label: 'Currency', mono: true },
      { key: 'sale_rate', label: 'Sale rate' },
      { key: 'cost_rate', label: 'Cost rate' },
    ],
    fields: [
      {
        name: 'service_type',
        label: 'Service type',
        type: 'select',
        required: true,
        options: [
          { value: 'AIR_EXPORT', label: 'Air Export' },
          { value: 'AIR_IMPORT', label: 'Air Import' },
          { value: 'SEA_FCL_EXPORT', label: 'Sea FCL Export' },
          { value: 'SEA_FCL_IMPORT', label: 'Sea FCL Import' },
          { value: 'SEA_LCL_EXPORT', label: 'Sea LCL Export' },
          { value: 'SEA_LCL_IMPORT', label: 'Sea LCL Import' },
          { value: 'LAND', label: 'Land' },
          { value: 'COURIER', label: 'Courier' },
          { value: 'CUSTOMS_CLEARANCE', label: 'Customs Clearance' },
          { value: 'NVOCC_EXPORT', label: 'NVOCC Export' },
          { value: 'NVOCC_IMPORT', label: 'NVOCC Import' },
          { value: 'SERVICE_JOB', label: 'Service Job' },
          { value: 'WAREHOUSE', label: 'Warehouse' },
        ],
      },
      {
        name: 'origin_port_id',
        label: 'Origin port',
        type: 'select',
        optionsFrom: 'ports',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'dest_port_id',
        label: 'Destination port',
        type: 'select',
        optionsFrom: 'ports',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'container_type_id',
        label: 'Container type',
        type: 'select',
        optionsFrom: 'container-types',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'charge_code_id',
        label: 'Charge code',
        type: 'select',
        required: true,
        optionsFrom: 'charge-codes',
        optionsValueKey: 'id',
        optionsLabelKey: 'code',
      },
      {
        name: 'customer_id',
        label: 'Customer (optional)',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'unit', label: 'Unit', type: 'text', placeholder: 'Per Container' },
      { name: 'sale_rate', label: 'Sale rate', type: 'number', required: true },
      { name: 'cost_rate', label: 'Cost rate', type: 'number', required: true },
      {
        name: 'currency_code',
        label: 'Currency',
        type: 'select',
        required: true,
        optionsFrom: 'currencies',
        optionsValueKey: 'code',
        optionsLabelKey: 'code',
      },
      { name: 'valid_from', label: 'Valid from', type: 'date', required: true },
      { name: 'valid_to', label: 'Valid to', type: 'date' },
      boolActive,
    ],
  },
  'zip-distances': {
    key: 'zip-distances',
    title: 'Zip Distance Master',
    basePath: MASTER_PATHS['zip-distances'],
    labelField: 'from_zip',
    supportsDelete: true,
    menuPath: '/quotations/zip-distance-master',
    columns: [
      { key: 'from_zip', label: 'From ZIP', mono: true },
      { key: 'to_zip', label: 'To ZIP', mono: true },
      { key: 'distance', label: 'Distance' },
      { key: 'unit', label: 'Unit' },
    ],
    fields: [
      { name: 'from_zip', label: 'From ZIP', type: 'text', required: true, mono: true },
      { name: 'from_city', label: 'From city', type: 'text' },
      { name: 'to_zip', label: 'To ZIP', type: 'text', required: true, mono: true },
      { name: 'to_city', label: 'To city', type: 'text' },
      { name: 'distance', label: 'Distance', type: 'number', required: true },
      { name: 'unit', label: 'Unit', type: 'text', placeholder: 'KM' },
      boolActive,
    ],
  },

  // ── Newly published Swagger masters ──
  regions: {
    key: 'regions',
    title: 'Region',
    basePath: MASTER_PATHS.regions,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'SEA' },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'South East Asia' },
      countryCodeField,
      boolActive,
    ],
  },
  cities: {
    key: 'cities',
    title: 'City',
    basePath: MASTER_PATHS.cities,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'region_id', label: 'Region', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      countryCodeField,
      {
        name: 'region_id',
        label: 'Region',
        type: 'select',
        optionsFrom: 'regions',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      boolActive,
    ],
  },
  zones: {
    key: 'zones',
    title: 'Zone',
    basePath: MASTER_PATHS.zones,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'region_id', label: 'Region', mono: true },
      { key: 'city_id', label: 'City', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'SZ' },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'South Zone' },
      {
        name: 'region_id',
        label: 'Region',
        type: 'select',
        optionsFrom: 'regions',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'city_id',
        label: 'City',
        type: 'select',
        optionsFrom: 'cities',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      boolActive,
    ],
  },
  divisions: {
    key: 'divisions',
    title: 'Division',
    basePath: MASTER_PATHS.divisions,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'company_id', label: 'Company', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      boolActive,
    ],
  },
  categories: {
    key: 'categories',
    title: 'Category Master',
    basePath: MASTER_PATHS.categories,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'category_type', label: 'Type' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'category_type',
        label: 'Category type',
        type: 'text',
        required: true,
        placeholder: 'ORIGIN_AGENT',
      },
      boolActive,
    ],
  },
  commodities: {
    key: 'commodities',
    title: 'Commodity',
    basePath: MASTER_PATHS.commodities,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'hs_code', label: 'HS code', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'hs_code', label: 'HS code', type: 'text', mono: true },
      boolActive,
    ],
  },
  packs: {
    key: 'packs',
    title: 'Pack',
    basePath: MASTER_PATHS.packs,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'length_cm', label: 'L (cm)' },
      { key: 'width_cm', label: 'W (cm)' },
      { key: 'height_cm', label: 'H (cm)' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'length_cm', label: 'Length (cm)', type: 'number' },
      { name: 'width_cm', label: 'Width (cm)', type: 'number' },
      { name: 'height_cm', label: 'Height (cm)', type: 'number' },
      boolActive,
    ],
  },
  clauses: {
    key: 'clauses',
    title: 'Clause Master',
    basePath: MASTER_PATHS.clauses,
    labelField: 'title',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'title', label: 'Title' },
      { key: 'clause_type', label: 'Type' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'body', label: 'Body', type: 'textarea', required: true },
      { name: 'clause_type', label: 'Clause type', type: 'text', placeholder: 'STAMP' },
      boolActive,
    ],
  },
  'port-clause-maps': {
    key: 'port-clause-maps',
    title: 'Port Clause Map',
    basePath: MASTER_PATHS['port-clause-maps'],
    labelField: 'id',
    supportsDelete: true,
    columns: [
      { key: 'port_id', label: 'Port', mono: true },
      { key: 'clause_id', label: 'Clause', mono: true },
    ],
    fields: [
      {
        name: 'port_id',
        label: 'Port',
        type: 'select',
        required: true,
        optionsFrom: 'ports',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'clause_id',
        label: 'Clause',
        type: 'select',
        required: true,
        optionsFrom: 'clauses',
        optionsValueKey: 'id',
        optionsLabelKey: 'title',
      },
      boolActive,
    ],
  },
  'rate-bases': {
    key: 'rate-bases',
    title: 'Rate Basis',
    basePath: MASTER_PATHS['rate-bases'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'LR' },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Per Pallet' },
      boolActive,
    ],
  },
  voyages: {
    key: 'voyages',
    title: 'Voyage Master List',
    basePath: MASTER_PATHS.voyages,
    labelField: 'voyage_code',
    supportsDelete: true,
    columns: [
      { key: 'voyage_code', label: 'Voyage', mono: true },
      { key: 'vessel_id', label: 'Vessel', mono: true },
      { key: 'shipping_line_id', label: 'Line', mono: true },
      { key: 'etd', label: 'ETD' },
      { key: 'eta', label: 'ETA' },
    ],
    fields: [
      { name: 'voyage_code', label: 'Voyage code', type: 'text', required: true, mono: true },
      {
        name: 'vessel_id',
        label: 'Vessel',
        type: 'select',
        optionsFrom: 'vessels',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'shipping_line_id',
        label: 'Shipping line',
        type: 'select',
        optionsFrom: 'shipping-lines',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'etd', label: 'ETD', type: 'date' },
      { name: 'eta', label: 'ETA', type: 'date' },
      boolActive,
    ],
  },
  'storage-slabs': {
    key: 'storage-slabs',
    title: 'Storage Slab Master',
    basePath: MASTER_PATHS['storage-slabs'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'from_days', label: 'From days' },
      { key: 'to_days', label: 'To days' },
      { key: 'rate', label: 'Rate' },
      { key: 'currency_code', label: 'Currency', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'from_days', label: 'From days', type: 'number', required: true },
      { name: 'to_days', label: 'To days', type: 'number', required: true },
      { name: 'rate', label: 'Rate', type: 'number', required: true },
      {
        name: 'rate_basis_id',
        label: 'Rate basis',
        type: 'select',
        optionsFrom: 'rate-bases',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'currency_code', label: 'Currency code', type: 'text', placeholder: 'AED' },
      boolActive,
    ],
  },
  activities: {
    key: 'activities',
    title: 'Activity Master',
    basePath: MASTER_PATHS.activities,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'module', label: 'Module' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'module', label: 'Module', type: 'text', placeholder: 'CONTAINER' },
      boolActive,
    ],
  },
  'sales-call-activities': {
    key: 'sales-call-activities',
    title: 'Sales Call Activity',
    basePath: MASTER_PATHS['sales-call-activities'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      boolActive,
    ],
  },
  'organization-groups': {
    key: 'organization-groups',
    title: 'Organization Group List',
    basePath: MASTER_PATHS['organization-groups'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'company_ids',
        label: 'Company IDs (CSV)',
        type: 'text',
        csvToArray: true,
        placeholder: 'uuid,uuid',
      },
      boolActive,
    ],
  },
  'custom-reports': {
    key: 'custom-reports',
    title: 'Custom Report Master',
    basePath: MASTER_PATHS['custom-reports'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'report_template_code', label: 'Template', mono: true },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'report_template_code',
        label: 'Report template code',
        type: 'text',
        required: true,
        mono: true,
      },
      boolActive,
    ],
  },
  favorites: {
    key: 'favorites',
    title: 'Favorites',
    basePath: MASTER_PATHS.favorites,
    labelField: 'label',
    supportsDelete: true,
    createOnly: true,
    columns: [
      { key: 'entity_type', label: 'Type' },
      { key: 'entity_id', label: 'Entity', mono: true },
      { key: 'label', label: 'Label' },
    ],
    fields: [
      { name: 'entity_type', label: 'Entity type', type: 'text', required: true },
      { name: 'entity_id', label: 'Entity ID', type: 'text', required: true, mono: true },
      { name: 'label', label: 'Label', type: 'text' },
    ],
  },
  'whatsapp-sms-history': {
    key: 'whatsapp-sms-history',
    title: 'WhatsApp SMS History',
    basePath: MASTER_PATHS['whatsapp-sms-history'],
    labelField: 'to_address',
    supportsDelete: false,
    createOnly: true,
    searchQueryKey: 'q',
    columns: [
      { key: 'channel', label: 'Channel' },
      { key: 'to_address', label: 'To' },
      { key: 'body_snippet', label: 'Snippet' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      {
        name: 'channel',
        label: 'Channel',
        type: 'select',
        required: true,
        options: [
          { value: 'whatsapp', label: 'WhatsApp' },
          { value: 'sms', label: 'SMS' },
        ],
      },
      { name: 'to_address', label: 'To address', type: 'text', required: true },
      { name: 'body_snippet', label: 'Body snippet', type: 'textarea', required: true },
      { name: 'status', label: 'Status', type: 'text', placeholder: 'SENT' },
    ],
  },

  // Read / search proxies
  'address-search': {
    key: 'address-search',
    title: 'Address Search',
    basePath: MASTER_PATHS['address-search'],
    labelField: 'line1',
    readOnly: true,
    requiresSearch: true,
    searchQueryKey: 'q',
    supportsDelete: false,
    columns: [
      { key: 'party_name', label: 'Party' },
      { key: 'line1', label: 'Address' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [],
  },
  'contacts-search': {
    key: 'contacts-search',
    title: 'Contacts Search',
    basePath: MASTER_PATHS['contacts-search'],
    labelField: 'name',
    readOnly: true,
    requiresSearch: true,
    searchQueryKey: 'q',
    supportsDelete: false,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'party_name', label: 'Party' },
    ],
    fields: [],
  },
  'attachments-search': {
    key: 'attachments-search',
    title: 'Attachments Search',
    basePath: MASTER_PATHS['attachments-search'],
    labelField: 'file_name',
    readOnly: true,
    requiresSearch: true,
    searchQueryKey: 'q',
    supportsDelete: false,
    columns: [
      { key: 'file_name', label: 'File' },
      { key: 'document_type', label: 'Type' },
      { key: 'job_number', label: 'Job' },
      { key: 'created_at', label: 'Created' },
    ],
    fields: [],
  },
  'container-inventory': {
    key: 'container-inventory',
    title: 'Container Inventory',
    basePath: MASTER_PATHS['container-inventory'],
    labelField: 'container_no',
    readOnly: true,
    supportsDelete: false,
    searchQueryKey: 'q',
    columns: [
      { key: 'container_no', label: 'Container', mono: true },
      { key: 'container_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'location', label: 'Location' },
      { key: 'free_days', label: 'Free days' },
    ],
    fields: [],
  },
  'tracking-users': {
    key: 'tracking-users',
    title: 'Tracking Users',
    basePath: MASTER_PATHS['tracking-users'],
    labelField: 'email',
    readOnly: true,
    supportsDelete: false,
    searchQueryKey: 'q',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'branch_name', label: 'Branch' },
    ],
    fields: [],
  },
  organization: {
    key: 'organization',
    title: 'Organization',
    basePath: MASTER_PATHS.organization,
    labelField: 'name',
    readOnly: true,
    supportsDelete: false,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'legal_name', label: 'Legal name' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'email', label: 'Email' },
    ],
    fields: [],
  },
  notifications: {
    key: 'notifications',
    title: 'Notifications',
    basePath: MASTER_PATHS.notifications,
    labelField: 'title',
    readOnly: true,
    supportsDelete: false,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'body', label: 'Body' },
      { key: 'is_read', label: 'Read' },
      { key: 'created_at', label: 'Created' },
    ],
    fields: [],
  },
};

/** Port mode variants that reuse /masters/ports with a default mode filter. */
export const PORT_MODE_ALIASES: Record<string, { title: string; mode: string }> = {
  seaport: { title: 'Seaport', mode: 'SEA' },
  landport: { title: 'Landport', mode: 'LAND' },
  airport: { title: 'Airport', mode: 'AIR' },
};

/** Legacy Masters menu paths → Swagger resource keys. */
export const MASTER_MENU_ALIASES: Record<string, MasterResourceKey> = {
  'activity-master': 'activities',
  'category-master': 'categories',
  city: 'cities',
  'clause-master': 'clauses',
  commodity: 'commodities',
  'custom-report-master': 'custom-reports',
  division: 'divisions',
  'organization-group-list': 'organization-groups',
  pack: 'packs',
  'port-clause-map': 'port-clause-maps',
  'rate-basis': 'rate-bases',
  region: 'regions',
  'sales-call-activity': 'sales-call-activities',
  'storage-slab-master': 'storage-slabs',
  'voyage-master-list': 'voyages',
  zone: 'zones',
};

export function getMasterResource(key: string): MasterResourceConfig | null {
  const resolved = MASTER_MENU_ALIASES[key] ?? key;
  if (resolved in MASTER_RESOURCES) {
    const base = MASTER_RESOURCES[resolved as MasterResourceKey];
    if (resolved === key) return base;
    return { ...base, key, menuPath: `/masters/${key}` };
  }
  // Alias: seaport / landport → ports with mode default
  if (key === 'seaport' || key === 'landport') {
    const alias = PORT_MODE_ALIASES[key];
    const base = MASTER_RESOURCES.ports;
    return {
      ...base,
      key,
      title: alias.title,
      listDefaults: { ...(base.listDefaults ?? {}), mode: alias.mode },
    };
  }
  return null;
}

export function listMasterResourceKeys(): MasterResourceKey[] {
  return Object.keys(MASTER_RESOURCES) as MasterResourceKey[];
}
