import type { MasterResourceConfig } from '../types/master.types';
import { MASTER_PATHS, type MasterResourceKey } from '../api/masterPaths';

const boolActive = {
  name: 'is_active',
  label: 'Active',
  type: 'boolean' as const,
};

const countryCodeField = {
  name: 'country_code',
  label: 'Country code',
  type: 'text' as const,
  placeholder: 'AE',
};

/** All Swagger-backed master resources. */
export const MASTER_RESOURCES: Record<MasterResourceKey, MasterResourceConfig> = {
  airlines: {
    key: 'airlines',
    title: 'Airlines',
    basePath: MASTER_PATHS.airlines,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'iata_code', label: 'IATA', mono: true },
      { key: 'icao_code', label: 'ICAO', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'iata_code', label: 'IATA code', type: 'text', required: true, mono: true },
      { name: 'icao_code', label: 'ICAO code', type: 'text', mono: true },
      { name: 'prefix_code', label: 'Prefix code', type: 'text' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      countryCodeField,
      boolActive,
    ],
  },
  airports: {
    key: 'airports',
    title: 'Airports',
    basePath: MASTER_PATHS.airports,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'iata_code', label: 'IATA', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'iata_code', label: 'IATA code', type: 'text', required: true, mono: true },
      { name: 'icao_code', label: 'ICAO code', type: 'text', mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text' },
      { ...countryCodeField, required: true },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Dubai' },
      boolActive,
    ],
  },
  banks: {
    key: 'banks',
    title: 'Banks',
    basePath: MASTER_PATHS.banks,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'short_name', label: 'Short name' },
      { key: 'swift_code', label: 'SWIFT', mono: true },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'short_name', label: 'Short name', type: 'text' },
      { name: 'swift_code', label: 'SWIFT code', type: 'text', mono: true },
      { name: 'iban_prefix', label: 'IBAN prefix', type: 'text' },
      countryCodeField,
      boolActive,
    ],
  },
  branches: {
    key: 'branches',
    title: 'Branches',
    basePath: MASTER_PATHS.branches,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'city', label: 'City', type: 'text' },
      countryCodeField,
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'is_head_office', label: 'Head office', type: 'boolean' },
      boolActive,
    ],
  },
  'charge-codes': {
    key: 'charge-codes',
    title: 'Charge Codes',
    basePath: MASTER_PATHS['charge-codes'],
    labelField: 'code',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'description', label: 'Description' },
      { key: 'charge_group', label: 'Group' },
      { key: 'unit', label: 'Unit' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'description', label: 'Description', type: 'text', required: true },
      {
        name: 'charge_group',
        label: 'Charge group',
        type: 'select',
        options: [
          { value: 'FREIGHT', label: 'Freight' },
          { value: 'LOCAL_CHARGES', label: 'Local charges' },
          { value: 'CUSTOMS', label: 'Customs' },
          { value: 'DOCUMENTATION', label: 'Documentation' },
          { value: 'HANDLING', label: 'Handling' },
          { value: 'STORAGE', label: 'Storage' },
          { value: 'DEMURRAGE', label: 'Demurrage' },
          { value: 'DETENTION', label: 'Detention' },
          { value: 'INSURANCE', label: 'Insurance' },
          { value: 'ORIGIN_CHARGES', label: 'Origin charges' },
          { value: 'DESTINATION_CHARGES', label: 'Destination charges' },
          { value: 'SURCHARGES', label: 'Surcharges' },
          { value: 'OTHER', label: 'Other' },
        ],
      },
      {
        name: 'applicable_modes',
        label: 'Applicable modes',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'AIR', label: 'Air' },
          { value: 'SEA', label: 'Sea' },
          { value: 'LAND', label: 'Land' },
          { value: 'COURIER', label: 'Courier' },
        ],
      },
      { name: 'tax_applicable', label: 'Tax applicable', type: 'boolean' },
      {
        name: 'tax_rate_id',
        label: 'Tax rate',
        type: 'select',
        optionsFrom: 'tax-rates',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
        placeholder: 'Optional — create Tax Rates first',
      },
      { name: 'gl_revenue_code', label: 'GL revenue code', type: 'text' },
      { name: 'gl_cost_code', label: 'GL cost code', type: 'text' },
      { name: 'unit', label: 'Unit', type: 'text' },
      { name: 'is_mandatory', label: 'Mandatory', type: 'boolean' },
      boolActive,
    ],
  },
  'container-types': {
    key: 'container-types',
    title: 'Container Types',
    basePath: MASTER_PATHS['container-types'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'size', label: 'Size' },
      { key: 'teu', label: 'TEU' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'size', label: 'Size', type: 'text', required: true, placeholder: '20ft' },
      { name: 'teu', label: 'TEU', type: 'number' },
      { name: 'max_payload', label: 'Max payload', type: 'number' },
      { name: 'volume_cbm', label: 'Volume (CBM)', type: 'number' },
      boolActive,
    ],
  },
  countries: {
    key: 'countries',
    title: 'Countries',
    basePath: MASTER_PATHS.countries,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'iso_code', label: 'ISO', mono: true },
      { key: 'iso3_code', label: 'ISO3', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'dial_code', label: 'Dial' },
      { key: 'region', label: 'Region' },
    ],
    fields: [
      { name: 'iso_code', label: 'ISO code', type: 'text', required: true, mono: true },
      { name: 'iso3_code', label: 'ISO3 code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'dial_code', label: 'Dial code', type: 'text', placeholder: '+971' },
      { name: 'region', label: 'Region', type: 'text', placeholder: 'Middle East' },
      boolActive,
    ],
  },
  currencies: {
    key: 'currencies',
    title: 'Currencies',
    basePath: MASTER_PATHS.currencies,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'symbol', label: 'Symbol' },
      { key: 'decimal_places', label: 'Decimals' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'symbol', label: 'Symbol', type: 'text', required: true },
      { name: 'decimal_places', label: 'Decimal places', type: 'number' },
      { name: 'is_base', label: 'Base currency', type: 'boolean' },
      boolActive,
    ],
  },
  departments: {
    key: 'departments',
    title: 'Departments',
    basePath: MASTER_PATHS.departments,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'parent_id', label: 'Parent department ID', type: 'text' },
      boolActive,
    ],
  },
  designations: {
    key: 'designations',
    title: 'Designations',
    basePath: MASTER_PATHS.designations,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'department_id', label: 'Department', mono: true },
    ],
    fields: [
      {
        name: 'company_id',
        label: 'Company',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'name', label: 'Name', type: 'text', required: true },
      {
        name: 'department_id',
        label: 'Department',
        type: 'select',
        optionsFrom: 'departments',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      boolActive,
    ],
  },
  'exchange-rates': {
    key: 'exchange-rates',
    title: 'Exchange Rates',
    basePath: MASTER_PATHS['exchange-rates'],
    labelField: 'rate',
    supportsDelete: false,
    createOnly: true,
    columns: [
      { key: 'currency_id', label: 'Currency', mono: true },
      { key: 'base_currency', label: 'Base', mono: true },
      { key: 'rate', label: 'Rate' },
      { key: 'rate_date', label: 'Date' },
    ],
    fields: [
      {
        name: 'currency_id',
        label: 'Currency',
        type: 'select',
        required: true,
        optionsFrom: 'currencies',
        optionsValueKey: 'id',
        optionsLabelKey: 'code',
      },
      { name: 'base_currency', label: 'Base currency', type: 'text', required: true, placeholder: 'AED' },
      { name: 'rate', label: 'Rate', type: 'number', required: true },
      { name: 'rate_date', label: 'Rate date', type: 'date', required: true },
      { name: 'source', label: 'Source', type: 'text' },
    ],
  },
  holidays: {
    key: 'holidays',
    title: 'Holidays',
    basePath: MASTER_PATHS.holidays,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'date', label: 'Date' },
      { key: 'country_code', label: 'Country', mono: true },
      { key: 'is_recurring', label: 'Recurring' },
    ],
    fields: [
      {
        name: 'country_code',
        label: 'Country',
        type: 'select',
        required: true,
        optionsFrom: 'countries',
        optionsValueKey: 'iso_code',
        optionsLabelKey: 'name',
        placeholder: 'Select country (create under Countries first)',
      },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'UAE National Day' },
      { name: 'is_recurring', label: 'Recurring yearly', type: 'boolean' },
    ],
  },
  'hs-codes': {
    key: 'hs-codes',
    title: 'HS Codes',
    basePath: MASTER_PATHS['hs-codes'],
    labelField: 'hs_code',
    supportsDelete: true,
    columns: [
      { key: 'hs_code', label: 'HS Code', mono: true },
      { key: 'description', label: 'Description' },
      { key: 'dg_class', label: 'DG class' },
    ],
    fields: [
      { name: 'hs_code', label: 'HS code', type: 'text', required: true, mono: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'import_duty_rate', label: 'Import duty rate', type: 'number' },
      { name: 'export_duty_rate', label: 'Export duty rate', type: 'number' },
      { name: 'dg_class', label: 'DG class', type: 'text' },
      { name: 'un_number', label: 'UN number', type: 'text' },
      { name: 'is_prohibited', label: 'Prohibited', type: 'boolean' },
      { name: 'is_restricted', label: 'Restricted', type: 'boolean' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
      boolActive,
    ],
  },
  ports: {
    key: 'ports',
    title: 'Ports',
    basePath: MASTER_PATHS.ports,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'un_locode', label: 'UNLOCODE', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'mode', label: 'Mode' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'un_locode', label: 'UNLOCODE', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text' },
      { ...countryCodeField, required: true },
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        options: [
          { value: 'SEA', label: 'Sea' },
          { value: 'AIR', label: 'Air' },
          { value: 'LAND', label: 'Land' },
        ],
      },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      boolActive,
    ],
  },
  'shipping-lines': {
    key: 'shipping-lines',
    title: 'Shipping Lines',
    basePath: MASTER_PATHS['shipping-lines'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'scac_code', label: 'SCAC', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'short_name', label: 'Short name' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'scac_code', label: 'SCAC code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'short_name', label: 'Short name', type: 'text' },
      countryCodeField,
      { name: 'website', label: 'Website', type: 'url' },
      { name: 'tracking_url', label: 'Tracking URL', type: 'url' },
      boolActive,
    ],
  },
  'tax-rates': {
    key: 'tax-rates',
    title: 'Tax Rates',
    basePath: MASTER_PATHS['tax-rates'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'rate', label: 'Rate' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'UAE VAT Standard' },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true, placeholder: 'VAT5' },
      {
        name: 'tax_type',
        label: 'Tax type',
        type: 'select',
        options: [
          { value: 'VAT', label: 'VAT' },
          { value: 'GST', label: 'GST' },
          { value: 'CUSTOMS', label: 'Customs' },
          { value: 'WITHHOLDING', label: 'Withholding' },
          { value: 'NONE', label: 'None' },
        ],
      },
      { name: 'rate', label: 'Rate (%)', type: 'number', required: true, placeholder: '5' },
      {
        name: 'country_code',
        label: 'Country',
        type: 'select',
        required: true,
        optionsFrom: 'countries',
        optionsValueKey: 'iso_code',
        optionsLabelKey: 'name',
      },
      { name: 'effective_from', label: 'Effective from', type: 'date', required: true },
      { name: 'effective_to', label: 'Effective to', type: 'date' },
      { name: 'is_default', label: 'Default', type: 'boolean' },
      boolActive,
    ],
  },
  truckers: {
    key: 'truckers',
    title: 'Truckers',
    basePath: MASTER_PATHS.truckers,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      countryCodeField,
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'contact_person', label: 'Contact person', type: 'text' },
      boolActive,
    ],
  },
  'units-of-measure': {
    key: 'units-of-measure',
    title: 'Units of Measure',
    basePath: MASTER_PATHS['units-of-measure'],
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
    ],
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true },
      boolActive,
    ],
  },
  vessels: {
    key: 'vessels',
    title: 'Vessels',
    basePath: MASTER_PATHS.vessels,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'imo_number', label: 'IMO', mono: true },
      { key: 'flag_country', label: 'Flag' },
      { key: 'vessel_type', label: 'Type' },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'imo_number', label: 'IMO number', type: 'text', mono: true },
      { name: 'flag_country', label: 'Flag country', type: 'text' },
      {
        name: 'shipping_line_id',
        label: 'Shipping line',
        type: 'select',
        optionsFrom: 'shipping-lines',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'vessel_type', label: 'Vessel type', type: 'text' },
      { name: 'year_built', label: 'Year built', type: 'number' },
      { name: 'gross_tonnage', label: 'Gross tonnage', type: 'number' },
      boolActive,
    ],
  },
  warehouses: {
    key: 'warehouses',
    title: 'Warehouses',
    basePath: MASTER_PATHS.warehouses,
    labelField: 'name',
    supportsDelete: true,
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'country_code', label: 'Country', mono: true },
    ],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, mono: true },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'city', label: 'City', type: 'text' },
      countryCodeField,
      { name: 'capacity_sqm', label: 'Capacity (sqm)', type: 'number' },
      boolActive,
    ],
  },
  tariffs: {
    key: 'tariffs',
    title: 'Online Tariff Master',
    basePath: MASTER_PATHS.tariffs,
    labelField: 'service_type',
    supportsDelete: true,
    menuPath: '/quotations/tariff-master',
    columns: [
      { key: 'service_type', label: 'Service' },
      { key: 'currency_code', label: 'Currency', mono: true },
      { key: 'sale_rate', label: 'Sale rate' },
      { key: 'cost_rate', label: 'Cost rate' },
    ],
    fields: [
      {
        name: 'service_type',
        label: 'Service type',
        type: 'select',
        required: true,
        options: [
          { value: 'AIR_EXPORT', label: 'Air Export' },
          { value: 'AIR_IMPORT', label: 'Air Import' },
          { value: 'SEA_FCL_EXPORT', label: 'Sea FCL Export' },
          { value: 'SEA_FCL_IMPORT', label: 'Sea FCL Import' },
          { value: 'SEA_LCL_EXPORT', label: 'Sea LCL Export' },
          { value: 'SEA_LCL_IMPORT', label: 'Sea LCL Import' },
          { value: 'LAND', label: 'Land' },
          { value: 'COURIER', label: 'Courier' },
          { value: 'CUSTOMS_CLEARANCE', label: 'Customs Clearance' },
          { value: 'NVOCC_EXPORT', label: 'NVOCC Export' },
          { value: 'NVOCC_IMPORT', label: 'NVOCC Import' },
          { value: 'SERVICE_JOB', label: 'Service Job' },
          { value: 'WAREHOUSE', label: 'Warehouse' },
        ],
      },
      {
        name: 'origin_port_id',
        label: 'Origin port',
        type: 'select',
        optionsFrom: 'ports',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'dest_port_id',
        label: 'Destination port',
        type: 'select',
        optionsFrom: 'ports',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'container_type_id',
        label: 'Container type',
        type: 'select',
        optionsFrom: 'container-types',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      {
        name: 'charge_code_id',
        label: 'Charge code',
        type: 'select',
        required: true,
        optionsFrom: 'charge-codes',
        optionsValueKey: 'id',
        optionsLabelKey: 'code',
      },
      {
        name: 'customer_id',
        label: 'Customer (optional)',
        type: 'select',
        optionsFrom: 'companies',
        optionsValueKey: 'id',
        optionsLabelKey: 'name',
      },
      { name: 'unit', label: 'Unit', type: 'text', placeholder: 'Per Container' },
      { name: 'sale_rate', label: 'Sale rate', type: 'number', required: true },
      { name: 'cost_rate', label: 'Cost rate', type: 'number', required: true },
      {
        name: 'currency_code',
        label: 'Currency',
        type: 'select',
        required: true,
        optionsFrom: 'currencies',
        optionsValueKey: 'code',
        optionsLabelKey: 'code',
      },
      { name: 'valid_from', label: 'Valid from', type: 'date', required: true },
      { name: 'valid_to', label: 'Valid to', type: 'date' },
      boolActive,
    ],
  },
  'zip-distances': {
    key: 'zip-distances',
    title: 'Zip Distance Master',
    basePath: MASTER_PATHS['zip-distances'],
    labelField: 'from_zip',
    supportsDelete: true,
    menuPath: '/quotations/zip-distance-master',
    columns: [
      { key: 'from_zip', label: 'From ZIP', mono: true },
      { key: 'to_zip', label: 'To ZIP', mono: true },
      { key: 'distance', label: 'Distance' },
      { key: 'unit', label: 'Unit' },
    ],
    fields: [
      { name: 'from_zip', label: 'From ZIP', type: 'text', required: true, mono: true },
      { name: 'from_city', label: 'From city', type: 'text' },
      { name: 'to_zip', label: 'To ZIP', type: 'text', required: true, mono: true },
      { name: 'to_city', label: 'To city', type: 'text' },
      { name: 'distance', label: 'Distance', type: 'number', required: true },
      { name: 'unit', label: 'Unit', type: 'text', placeholder: 'KM' },
      boolActive,
    ],
  },
};

/** Port mode variants that reuse /masters/ports with a default mode filter. */
export const PORT_MODE_ALIASES: Record<string, { title: string; mode: string }> = {
  seaport: { title: 'Seaport', mode: 'SEA' },
  landport: { title: 'Landport', mode: 'LAND' },
  airport: { title: 'Airport', mode: 'AIR' },
};

export function getMasterResource(key: string): MasterResourceConfig | null {
  if (key in MASTER_RESOURCES) {
    return MASTER_RESOURCES[key as MasterResourceKey];
  }
  // Alias: seaport / landport → ports with mode default
  if (key === 'seaport' || key === 'landport') {
    const alias = PORT_MODE_ALIASES[key];
    const base = MASTER_RESOURCES.ports;
    return {
      ...base,
      key,
      title: alias.title,
      listDefaults: { ...(base.listDefaults ?? {}), mode: alias.mode },
    };
  }
  return null;
}

export function listMasterResourceKeys(): MasterResourceKey[] {
  return Object.keys(MASTER_RESOURCES) as MasterResourceKey[];
}
