import {
  Barcode, Activity, Home, Plane, Paperclip, Tag, Building2, BookOpen, Package, Users, Boxes, Container,
  Globe, DollarSign, FileEdit, IdCard, Layers, Star, Hash, Anchor,
  Bell, Building, Users2, PackageOpen, MapPinned, Ship, Percent, Map,
  PhoneCall, Waves, Warehouse, UserCheck, ShipWheel, Route, MessageSquare, Globe2,
  PlaneTakeoff, Landmark, GitBranch, Receipt, Building as BuildingIcon, CalendarDays,
  Truck, Ruler, ArrowLeftRight,
} from 'lucide-react';
import type { MenuTile } from '../../customers/types/menu.types';

/** Masters hub tiles — all paths map to Swagger-backed `/masters/*` (or AWB stock). */
export const mastersMenu: MenuTile[] = [
  { id: 'airlines', title: 'Airlines', description: 'Airline IATA/ICAO codes and prefixes.', icon: PlaneTakeoff, iconColor: 'bg-sky-600', path: '/masters/airlines' },
  { id: 'airports', title: 'Airports', description: 'To maintain airport details such as IATA code, city, country and timezone.', icon: Plane, iconColor: 'bg-green-600', path: '/masters/airports' },
  { id: 'banks', title: 'Banks', description: 'Bank master with SWIFT and country codes.', icon: Landmark, iconColor: 'bg-emerald-600', path: '/masters/banks' },
  { id: 'branches', title: 'Branches', description: 'Company branches and head-office flags.', icon: GitBranch, iconColor: 'bg-teal-600', path: '/masters/branches' },
  { id: 'charge-codes', title: 'Charge Codes', description: 'Charge codes, tax links and GL mapping.', icon: Receipt, iconColor: 'bg-amber-600', path: '/masters/charge-codes' },
  { id: 'container-types', title: 'Container Type', description: 'To maintain container details such as container type, volume, weight and TEU.', icon: Container, iconColor: 'bg-purple-600', path: '/masters/container-types' },
  { id: 'courier-vendors', title: 'Courier Vendors', description: 'Courier / express vendors with tracking URL templates.', icon: Truck, iconColor: 'bg-orange-600', path: '/masters/courier-vendors' },
  { id: 'countries', title: 'Country', description: 'To maintain country details such as ISO codes, dial code and region.', icon: Globe, iconColor: 'bg-purple-500', path: '/masters/countries' },
  { id: 'currencies', title: 'Currency', description: 'To maintain currency code, name, symbol and decimals.', icon: DollarSign, iconColor: 'bg-gray-500', path: '/masters/currencies' },
  { id: 'departments', title: 'Departments', description: 'Company departments and hierarchy.', icon: BuildingIcon, iconColor: 'bg-indigo-500', path: '/masters/departments' },
  { id: 'designations', title: 'Designation', description: 'To maintain employee designation details.', icon: IdCard, iconColor: 'bg-blue-500', path: '/masters/designations' },
  { id: 'exchange-rates', title: 'Exchange Rates', description: 'Currency exchange rates by date.', icon: ArrowLeftRight, iconColor: 'bg-cyan-600', path: '/masters/exchange-rates' },
  { id: 'holidays', title: 'Holidays', description: 'Country holiday calendar.', icon: CalendarDays, iconColor: 'bg-rose-500', path: '/masters/holidays' },
  { id: 'hs-codes', title: 'HS Codes', description: 'To maintain HS Code details, duties and DG class.', icon: Hash, iconColor: 'bg-green-500', path: '/masters/hs-codes' },
  { id: 'ports', title: 'Ports', description: 'To maintain ports details (sea, air, land) with UNLOCODE.', icon: Ship, iconColor: 'bg-purple-500', path: '/masters/ports' },
  { id: 'seaport', title: 'Seaport', description: 'Sea ports filtered from the ports master.', icon: Waves, iconColor: 'bg-blue-500', path: '/masters/seaport' },
  { id: 'landport', title: 'Landport', description: 'Land ports filtered from the ports master.', icon: Anchor, iconColor: 'bg-lime-500', path: '/masters/landport' },
  { id: 'shipping-lines', title: 'Shipping Lines', description: 'Ocean carriers with SCAC and tracking URLs.', icon: Ship, iconColor: 'bg-blue-700', path: '/masters/shipping-lines' },
  { id: 'tax-rates', title: 'Tax Rates', description: 'Tax rate master by country and effective dates.', icon: Percent, iconColor: 'bg-orange-500', path: '/masters/tax-rates' },
  { id: 'truckers', title: 'Truckers', description: 'Trucker / haulier master records.', icon: Truck, iconColor: 'bg-stone-600', path: '/masters/truckers' },
  { id: 'units-of-measure', title: 'Units of Measure', description: 'UOM codes and categories.', icon: Ruler, iconColor: 'bg-slate-500', path: '/masters/units-of-measure' },
  { id: 'vessels', title: 'Vessel List', description: 'To maintain vessel details such as name, IMO, type and flag.', icon: ShipWheel, iconColor: 'bg-blue-500', path: '/masters/vessels' },
  { id: 'warehouses', title: 'Warehouses', description: 'Warehouse locations and capacity.', icon: Warehouse, iconColor: 'bg-teal-500', path: '/masters/warehouses' },
  { id: 'awb-stock-master', title: 'AWB Stock Master', description: 'To maintain airline AWB number stock and generate a series of numbers.', icon: Barcode, iconColor: 'bg-sky-500', path: '/masters/awb-stock-master' },

  { id: 'activities', title: 'Activity Master', description: 'To maintain all the activities like container activity, documentation, customer service and etc.', icon: Activity, iconColor: 'bg-teal-500', path: '/masters/activities' },
  { id: 'address-search', title: 'Address Search', description: 'Search party addresses across the tenant.', icon: Home, iconColor: 'bg-emerald-400', path: '/masters/address-search' },
  { id: 'attachments-search', title: 'Attachments Search', description: 'Search job & shipment document metadata.', icon: Paperclip, iconColor: 'bg-green-500', path: '/masters/attachments-search' },
  { id: 'categories', title: 'Category Master', description: 'To Maintain All The Categories Such As Origin Agent, Delivery Agent, Shipper And Etc.', icon: Tag, iconColor: 'bg-yellow-500', path: '/masters/categories' },
  { id: 'cities', title: 'City', description: 'To maintain city details such as code, name, region and country.', icon: Building2, iconColor: 'bg-orange-500', path: '/masters/cities' },
  { id: 'clauses', title: 'Clause Master', description: 'List to Add and Edit Clause, Stamp and Provision', icon: BookOpen, iconColor: 'bg-orange-600', path: '/masters/clauses' },
  { id: 'commodities', title: 'Commodity', description: 'To maintain all the commodity details such as code, name and HS code.', icon: Package, iconColor: 'bg-red-500', path: '/masters/commodities' },
  { id: 'contacts-search', title: 'Contacts Search', description: 'Search party contacts across the tenant.', icon: Users, iconColor: 'bg-pink-500', path: '/masters/contacts-search' },
  { id: 'container-inventory', title: 'Container Inventory', description: 'Job containers with free-days (read model).', icon: Boxes, iconColor: 'bg-purple-500', path: '/masters/container-inventory' },
  { id: 'custom-reports', title: 'Custom Report Master', description: 'To maintain custom report alignment and column details here', icon: FileEdit, iconColor: 'bg-teal-500', path: '/masters/custom-reports' },
  { id: 'divisions', title: 'Division', description: 'To maintain division details such as division code, name (Freight Forwarding, Warehouse) and etc.', icon: Layers, iconColor: 'bg-blue-500', path: '/masters/divisions' },
  { id: 'favorites', title: 'Favorites', description: "Favorites maintains the user's bookmarks.", icon: Star, iconColor: 'bg-teal-500', path: '/masters/favorites' },
  { id: 'notifications', title: 'Notifications', description: 'Current-user notification messages.', icon: Bell, iconColor: 'bg-yellow-500', path: '/masters/notifications' },
  { id: 'organization', title: 'Organization', description: 'Organization profile (read via masters proxy).', icon: Building, iconColor: 'bg-pink-500', path: '/masters/organization' },
  { id: 'organization-groups', title: 'Organization Group List', description: 'To maintain organization group details such as code, name and companies.', icon: Users2, iconColor: 'bg-red-500', path: '/masters/organization-groups' },
  { id: 'packs', title: 'Pack', description: 'To maintain package details such as bundles, bags, boxes, pallets and etc.', icon: PackageOpen, iconColor: 'bg-red-400', path: '/masters/packs' },
  { id: 'port-clause-maps', title: 'Port Clause Map', description: 'To Map Clauses/ Stamps/ Provisions to Ports', icon: MapPinned, iconColor: 'bg-pink-500', path: '/masters/port-clause-maps' },
  { id: 'rate-bases', title: 'Rate Basis', description: 'To maintain rate details such as rate code and rate name.', icon: Percent, iconColor: 'bg-purple-500', path: '/masters/rate-bases' },
  { id: 'regions', title: 'Region', description: 'To maintain region details such as region code and region name.', icon: Map, iconColor: 'bg-indigo-500', path: '/masters/regions' },
  { id: 'sales-call-activities', title: 'Sales Call Activity', description: 'To maintain sales call activity list.', icon: PhoneCall, iconColor: 'bg-gray-500', path: '/masters/sales-call-activities' },
  { id: 'storage-slabs', title: 'Storage Slab Master', description: 'To maintain the Storage slab details with rate and day ranges.', icon: Warehouse, iconColor: 'bg-teal-500', path: '/masters/storage-slabs' },
  { id: 'tracking-users', title: 'Tracking Users', description: 'Staff users flagged for ops / CS / sales tracking.', icon: UserCheck, iconColor: 'bg-blue-500', path: '/masters/tracking-users' },
  { id: 'voyages', title: 'Voyage Master List', description: 'To maintain voyage master list', icon: Route, iconColor: 'bg-green-500', path: '/masters/voyages' },
  { id: 'whatsapp-sms-history', title: 'WhatsApp SMS History', description: 'To View and Maintain WhatsApp and SMS History', icon: MessageSquare, iconColor: 'bg-green-500', path: '/masters/whatsapp-sms-history' },
  { id: 'zones', title: 'Zone', description: 'To maintain zone details such as zone code and zone name.', icon: Globe2, iconColor: 'bg-yellow-500', path: '/masters/zones' },
];
