import {
  BookOpen, LayoutDashboard, FileCheck, Home, Receipt, Ship, Container,
  Anchor, Package, Truck, FileSpreadsheet, Download, FileText, DollarSign,
  MapPin, RefreshCw, CheckSquare, FileBarChart,
} from 'lucide-react';
import type { MenuTile } from '../../customers/types/menu.types';

export const documentationMenu: MenuTile[] = [
  {
    id: 'all-jobs',
    title: 'All Jobs',
    description: 'To view all the jobs list by salesperson wise, customer wise and report segment wise.',
    icon: BookOpen,
    iconColor: 'bg-sky-500',
    path: '/documentation/all-jobs',
  },
  {
    id: 'boe-dashboard',
    title: 'BOE Dashboard',
    description: 'You can view the BOE details with BOE number and date, and open jobs details along with BOE number.',
    icon: LayoutDashboard,
    iconColor: 'bg-sky-500',
    path: '/documentation/boe-dashboard',
  },
  {
    id: 'bayan-edi-job-list',
    title: 'Bayan EDI Job List',
    description: 'Oman Customs Bayan EDI can download and Submit or Amendment for existing EDI.',
    icon: FileCheck,
    iconColor: 'bg-teal-500',
    path: '/documentation/bayan-edi-job-list',
  },
  {
    id: 'bayan-edi-shipment-house-list',
    title: 'Bayan EDI Shipment (House) List',
    description: 'Oman Customs Bayan EDI can download for Listed House.',
    icon: Home,
    iconColor: 'bg-emerald-500',
    path: '/documentation/bayan-edi-shipment-house-list',
  },
  {
    id: 'bulk-cost-entry',
    title: 'Bulk Cost Entry',
    description: 'To enter cost for more than one shipment and job.',
    icon: Receipt,
    iconColor: 'bg-green-500',
    path: '/documentation/bulk-cost-entry',
  },
  {
    id: 'ccn-fwb-fhl-edi-job-list',
    title: 'CCN FWB/FHL EDI Job List',
    description: 'Singapore Customs FWB/FHL EDI can download and submit for Listed Master/House jobs.',
    icon: FileSpreadsheet,
    iconColor: 'bg-yellow-500',
    path: '/documentation/ccn-fwb-fhl-edi-job-list',
  },
  {
    id: 'cgm-edi-vessel-list',
    title: 'CGM EDI Vessel List',
    description: 'User can download CGM EDI for multiple jobs based on vessel name and voyage number.',
    icon: Ship,
    iconColor: 'bg-yellow-500',
    path: '/documentation/cgm-edi-vessel-list',
  },
  {
    id: 'cargo-tracking-air',
    title: 'Cargo Tracking - Air',
    description: 'To track with MAWB No.',
    icon: MapPin,
    iconColor: 'bg-orange-500',
    path: '/documentation/cargo-tracking-air',
  },
  {
    id: 'charge-template-list',
    title: 'Charge Template List',
    description: 'Users can define charge templates based on their requirements. While generating a job, shipment, or quote, they can select the charges from the list of predefined templates.',
    icon: FileText,
    iconColor: 'bg-red-500',
    path: '/documentation/charge-template-list',
  },
  {
    id: 'container-no-upload',
    title: 'Container No. Upload',
    description: 'Container no upload is to upload the container no for different jobs, from given standard excel sheet.',
    icon: Container,
    iconColor: 'bg-pink-500',
    path: '/documentation/container-no-upload',
  },
  {
    id: 'container-transport-upload',
    title: 'Container Transport Upload',
    description: 'Container Transport upload is to upload the container handling charges and driver charge, driver name and etc from given standard excel sheet.',
    icon: Truck,
    iconColor: 'bg-pink-600',
    path: '/documentation/container-transport-upload',
  },
  {
    id: 'dpword-tracking-file-upload',
    title: 'DPWORD Tracking file upload',
    description: 'To upload csv file, text file by using this menu and extract the data.',
    icon: Download,
    iconColor: 'bg-purple-600',
    path: '/documentation/dpword-tracking-file-upload',
  },
  {
    id: 'dubai-eqo-edi',
    title: 'Dubai eQO EDI',
    description: 'Dubai Trade eQO BOL EDI',
    icon: Anchor,
    iconColor: 'bg-indigo-600',
    path: '/documentation/dubai-eqo-edi',
  },
  {
    id: 'export-air',
    title: 'Export-Air',
    description: 'To view an export jobs list and create a new air export job through this menu.',
    icon: Package,
    iconColor: 'bg-gray-400',
    path: '/documentation/export-air',
  },
  {
    id: 'ial-edi-job-list',
    title: 'IAL EDI Job List',
    description: 'This EDI for India Shippers/Forwarders, its provided based on India ICEGATE EDI format.',
    icon: FileCheck,
    iconColor: 'bg-gray-500',
    path: '/documentation/ial-edi-job-list',
  },
  {
    id: 'job-download',
    title: 'Job Download',
    description: 'Through this option you can download the job from company to and branch to branch.',
    icon: Download,
    iconColor: 'bg-sky-500',
    path: '/documentation/job-download',
  },
  {
    id: 'oman-eqo-edi',
    title: 'Oman eQO EDI',
    description: 'Oman eQO EDI',
    icon: Anchor,
    iconColor: 'bg-teal-500',
    path: '/documentation/oman-eqo-edi',
  },
  {
    id: 'payment-request-monitor',
    title: 'Payment Request Monitor',
    description: 'To view all the payment Request list and to create pending payment Requests to internal team for to pay the pending voucher.',
    icon: DollarSign,
    iconColor: 'bg-emerald-500',
    path: '/documentation/payment-request-monitor',
  },
  {
    id: 'sea-export-fcl',
    title: 'Sea Export-FCL',
    description: 'To view sea export-FCL job list and create a new sea export-FCL job through this menu.',
    icon: Ship,
    iconColor: 'bg-emerald-500',
    path: '/documentation/sea-export-fcl',
  },
  {
    id: 'sea-export-lcl',
    title: 'Sea Export-LCL',
    description: 'To view sea export-LCL job list and create a new sea export-LCL job through this menu.',
    icon: Ship,
    iconColor: 'bg-lime-500',
    path: '/documentation/sea-export-lcl',
  },
  {
    id: 'truck-position-upload',
    title: 'Truck Position Upload',
    description: 'Truck position upload is to upload the current position of truck details, driver name and etc from given standard excel sheet.',
    icon: Truck,
    iconColor: 'bg-yellow-500',
    path: '/documentation/truck-position-upload',
  },
  {
    id: 'uae-mpci-monitor',
    title: 'UAE MPCI Monitor',
    description: 'To View, prepare, Monitor and submission of MPCI Filings for UAE customs compliance, ensuring file submission',
    icon: RefreshCw,
    iconColor: 'bg-yellow-500',
    path: '/documentation/uae-mpci-monitor',
  },
  {
    id: 'update-do-closed-job',
    title: 'Update DO - Closed Job',
    description: 'Update DO No, DO Date, DO Status for Closed Export Jobs from this Menu.',
    icon: CheckSquare,
    iconColor: 'bg-orange-500',
    path: '/documentation/update-do-closed-job',
  },
  {
    id: 'voucher-batch-processing',
    title: 'Voucher Batch Processing',
    description: 'Batch processing is a bulk status change process from any status to status in a single click.',
    icon: RefreshCw,
    iconColor: 'bg-red-400',
    path: '/documentation/voucher-batch-processing',
  },
];

// Rendered separately with the centered layout, same pattern as other Reports tiles
export const reportsDocsTile: MenuTile = {
  id: 'reports-docs',
  title: 'Reports - Docs',
  description: 'To view all the reports related to Documentation by using this option, Jobs List, ETA followup, ETD Followup and etc.',
  icon: FileBarChart,
  iconColor: 'bg-sky-500',
  path: '/documentation/reports',
};