export const NVOCC_API = {
  tariffs: {
    list: '/nvocc/tariffs',
    lookup: '/nvocc/tariffs/lookup',
    create: '/nvocc/tariffs',
    byId: (id: string) => `/nvocc/tariffs/${id}`,
  },
  voyages: {
    list: '/nvocc/voyages',
    create: '/nvocc/voyages',
    byId: (id: string) => `/nvocc/voyages/${id}`,
    publish: (id: string) => `/nvocc/voyages/${id}/publish`,
    close: (id: string) => `/nvocc/voyages/${id}/close`,
    markSailed: (id: string) => `/nvocc/voyages/${id}/mark-sailed`,
    copy: (id: string) => `/nvocc/voyages/${id}/copy`,
    loadList: (id: string) => `/nvocc/voyages/${id}/load-list`,
    loadListWeightCheck: (id: string) => `/nvocc/voyages/${id}/load-list/weight-check`,
    loadListPdf: (id: string) => `/nvocc/voyages/${id}/load-list/pdf`,
    pnl: (id: string) => `/nvocc/voyages/${id}/pnl`,
    loadListItem: (voyageId: string, itemId: string) =>
      `/nvocc/voyages/${voyageId}/load-list/${itemId}`,
    assignContainer: (voyageId: string, itemId: string) =>
      `/nvocc/voyages/${voyageId}/load-list/${itemId}/assign-container`,
  },
  enquiries: {
    list: '/nvocc/enquiries',
    analytics: '/nvocc/enquiries/analytics',
    create: '/nvocc/enquiries',
    byId: (id: string) => `/nvocc/enquiries/${id}`,
    sendRate: (id: string) => `/nvocc/enquiries/${id}/send-rate`,
    markLost: (id: string) => `/nvocc/enquiries/${id}/mark-lost`,
    convertToBooking: (id: string) => `/nvocc/enquiries/${id}/convert-to-booking`,
  },
  bookings: {
    list: '/nvocc/bookings',
    create: '/nvocc/bookings',
    byId: (id: string) => `/nvocc/bookings/${id}`,
    confirm: (id: string) => `/nvocc/bookings/${id}/confirm`,
    cancel: (id: string) => `/nvocc/bookings/${id}/cancel`,
    convertToJob: (id: string) => `/nvocc/bookings/${id}/convert-to-job`,
    sendCutoffReminder: (id: string) => `/nvocc/bookings/${id}/send-cutoff-reminder`,
    bookingConfirmation: (id: string) => `/nvocc/bookings/${id}/documents/booking-confirmation`,
    csTriage: (id: string) => `/nvocc/bookings/${id}/cs-triage`,
    markQuoteSent: (id: string) => `/nvocc/bookings/${id}/mark-quote-sent`,
    bookingForm: (id: string) => `/nvocc/bookings/${id}/booking-form`,
    sendInvoice: (id: string) => `/nvocc/bookings/${id}/send-invoice`,
  },
  jobs: {
    generationStatus: (id: string) => `/nvocc/jobs/${id}/documents/generation-status`,
    hblDraft: (id: string) => `/nvocc/jobs/${id}/documents/hbl-draft`,
    hblOriginal: (id: string) => `/nvocc/jobs/${id}/documents/hbl-original`,
    hblDraftGated: (id: string) => `/nvocc/jobs/${id}/documents/hbl-draft-gated`,
    hblOriginalGated: (id: string) => `/nvocc/jobs/${id}/documents/hbl-original-gated`,
    hblExpressRelease: (id: string) => `/nvocc/jobs/${id}/documents/hbl-express-release`,
    surrenderNotice: (id: string) => `/nvocc/jobs/${id}/documents/surrender-notice`,
    mbl: (id: string) => `/nvocc/jobs/${id}/documents/mbl`,
    preCan: (id: string) => `/nvocc/jobs/${id}/documents/pre-can`,
    can: (id: string) => `/nvocc/jobs/${id}/documents/can`,
    deliveryOrder: (id: string) => `/nvocc/jobs/${id}/documents/delivery-order`,
    preAlertPdf: (id: string) => `/nvocc/jobs/${id}/documents/pre-alert`,
    bookingConfirmation: (id: string) => `/nvocc/jobs/${id}/documents/booking-confirmation`,
    stuffingReport: (id: string) => `/nvocc/jobs/${id}/documents/stuffing-report`,
    cargoManifest: (id: string) => `/nvocc/jobs/${id}/documents/cargo-manifest`,
    jobCard: (id: string) => `/nvocc/jobs/${id}/documents/job-card`,
    jobPnl: (id: string) => `/nvocc/jobs/${id}/documents/job-pnl`,
    proformaInvoice: (id: string) => `/nvocc/jobs/${id}/documents/proforma-invoice`,
    mblReceived: (id: string) => `/nvocc/jobs/${id}/mbl-received`,
    sendPreAlert: (id: string) => `/nvocc/jobs/${id}/pre-alert/send`,
    submitSi: (id: string) => `/nvocc/jobs/${id}/si/submit`,
    submitVgm: (id: string) => `/nvocc/jobs/${id}/vgm/submit`,
    podReceived: (id: string) => `/nvocc/jobs/${id}/pod/received`,
    containerRequests: (id: string) => `/nvocc/jobs/${id}/container-requests`,
    issueContainerRequest: (jobId: string, requestId: string) =>
      `/nvocc/jobs/${jobId}/container-requests/${requestId}/issue`,
    allocateContainerRequest: (jobId: string, requestId: string) =>
      `/nvocc/jobs/${jobId}/container-requests/${requestId}/allocate`,
    stageLoading: (id: string) => `/nvocc/jobs/${id}/stage/loading`,
    confirmPayment: (id: string) => `/nvocc/jobs/${id}/accounts/confirm-payment`,
    closeReport: (id: string) => `/nvocc/jobs/${id}/close-report`,
  },
  reports: {
    tradeLaneProfitability: '/nvocc/reports/trade-lane-profitability',
    utilization: '/nvocc/voyages/utilization',
  },
} as const;
