import type { CreateChartOfAccountDto } from '../types/chartOfAccount.types';

/**
 * Demo payloads matching CreateChartOfAccountDto (Swagger).
 * Use as form defaults / seed examples — not hardcoded runtime list data.
 */
export const CHART_OF_ACCOUNT_DEMO_CREATE: CreateChartOfAccountDto = {
  account_code: '1100',
  account_name: 'Trade Receivables',
  account_name_ar: undefined,
  account_group: 'ASSETS',
  account_type: 'CURRENT_ASSET',
  account_sub_type: 'TRADE_RECEIVABLE',
  is_header: false,
  is_postable: true,
  is_bank_account: false,
  is_cash_account: false,
  currency_code: 'AED',
  opening_balance: 0,
  opening_balance_type: 'DEBIT',
  allow_manual_entry: true,
  is_active: true,
  sort_order: 1100,
  notes: 'Customer AR for freight invoices',
};

export const CHART_OF_ACCOUNT_DEMO_SET: CreateChartOfAccountDto[] = [
  {
    account_code: '1000',
    account_name: 'Current Assets',
    account_group: 'ASSETS',
    account_type: 'CURRENT_ASSET',
    account_sub_type: 'GENERAL',
    is_header: true,
    is_postable: false,
    allow_manual_entry: false,
    is_active: true,
    sort_order: 1000,
    notes: 'Header — current assets',
  },
  {
    account_code: '1010',
    account_name: 'Cash on Hand',
    account_group: 'ASSETS',
    account_type: 'CURRENT_ASSET',
    account_sub_type: 'CASH',
    is_header: false,
    is_postable: true,
    is_cash_account: true,
    currency_code: 'AED',
    opening_balance: 5000,
    opening_balance_type: 'DEBIT',
    allow_manual_entry: true,
    is_active: true,
    sort_order: 1010,
  },
  {
    account_code: '1020',
    account_name: 'Bank — Operating AED',
    account_group: 'ASSETS',
    account_type: 'CURRENT_ASSET',
    account_sub_type: 'BANK',
    is_header: false,
    is_postable: true,
    is_bank_account: true,
    currency_code: 'AED',
    opening_balance: 125000,
    opening_balance_type: 'DEBIT',
    allow_manual_entry: true,
    is_active: true,
    sort_order: 1020,
  },
  {
    ...CHART_OF_ACCOUNT_DEMO_CREATE,
  },
  {
    account_code: '2000',
    account_name: 'Trade Payables',
    account_group: 'LIABILITIES',
    account_type: 'CURRENT_LIABILITY',
    account_sub_type: 'TRADE_PAYABLE',
    is_postable: true,
    currency_code: 'AED',
    opening_balance: 0,
    opening_balance_type: 'CREDIT',
    allow_manual_entry: true,
    is_active: true,
    sort_order: 2000,
    notes: 'Vendor AP for carriers and agents',
  },
  {
    account_code: '4000',
    account_name: 'Freight Revenue',
    account_group: 'REVENUE',
    account_type: 'REVENUE',
    account_sub_type: 'REVENUE',
    is_postable: true,
    currency_code: 'AED',
    opening_balance: 0,
    opening_balance_type: 'CREDIT',
    allow_manual_entry: true,
    is_active: true,
    sort_order: 4000,
  },
  {
    account_code: '5000',
    account_name: 'Cost of Sales — Ocean Freight',
    account_group: 'EXPENSES',
    account_type: 'COST_OF_SALES',
    account_sub_type: 'EXPENSE',
    is_postable: true,
    currency_code: 'AED',
    opening_balance: 0,
    opening_balance_type: 'DEBIT',
    allow_manual_entry: true,
    is_active: true,
    sort_order: 5000,
  },
];
