/** HR REST paths — Swagger tags "HR Employees", "HR Leave", "HR Payroll", etc. */
export const HR_API = {
  employees: '/hr/employees',
  employee: (id: string) => `/hr/employees/${id}`,
  employeeDependents: (id: string) => `/hr/employees/${id}/dependents`,
  employeeDocuments: (id: string) => `/hr/employees/${id}/documents`,
  employeeDocument: (id: string, docId: string) => `/hr/employees/${id}/documents/${docId}`,
  employeeEmploymentHistory: (id: string) => `/hr/employees/${id}/employment-history`,
  employeeQualifications: (id: string) => `/hr/employees/${id}/qualifications`,
  employeeSkills: (id: string) => `/hr/employees/${id}/skills`,
  employeeLinkUser: (id: string) => `/hr/employees/${id}/link-user`,
  employeeGratuity: (employeeId: string) => `/hr/employees/${employeeId}/gratuity`,
  employeeLeaveBalances: (employeeId: string) => `/hr/employees/${employeeId}/leave-balances`,
  employeeLeaveEncashment: (employeeId: string) => `/hr/employees/${employeeId}/leave-encashment`,

  leaveRequests: '/hr/leave-requests',
  leaveRequestApprove: (id: string) => `/hr/leave-requests/${id}/approve`,
  leaveRequestReject: (id: string) => `/hr/leave-requests/${id}/reject`,
  leaveRequestReturn: (id: string) => `/hr/leave-requests/${id}/return`,
  leaveRequestReview: (id: string) => `/hr/leave-requests/${id}/review`,
  leaveCalendar: '/hr/leave-calendar',
  leavePolicies: '/hr/leave-policies',
  leavePolicy: (id: string) => `/hr/leave-policies/${id}`,
  absentReport: '/hr/absent-report',
  documentExpiryReport: '/hr/document-expiry/report',

  payrollRuns: '/hr/payroll-runs',
  payrollRun: (id: string) => `/hr/payroll-runs/${id}`,
  payrollRunFinalize: (id: string) => `/hr/payroll-runs/${id}/finalize`,
  payrollRunGenerate: (id: string) => `/hr/payroll-runs/${id}/generate`,
  payrollRunGenerateLines: (id: string) => `/hr/payroll-runs/${id}/generate-lines`,
  payrollRunPostGl: (id: string) => `/hr/payroll-runs/${id}/post-gl`,
  payrollRunWpsExport: (id: string) => `/hr/payroll-runs/${id}/wps-export`,
  payrollRunWpsSif: (id: string) => `/hr/payroll-runs/${id}/wps-sif`,
  payrollPayslip: (runId: string, employeeId: string) =>
    `/hr/payroll-runs/${runId}/payslips/${employeeId}`,
  payrollPayslipEmail: (runId: string, employeeId: string) =>
    `/hr/payroll-runs/${runId}/payslips/${employeeId}/email`,
  payrollGlSettings: '/hr/payroll-gl-settings',
  salaryComponents: '/hr/salary-components',
  salaryComponentsSeed: '/hr/salary-components/seed',
  gratuity: '/hr/gratuity',

  attendance: '/hr/attendance',
  attendanceClockIn: '/hr/attendance/clock-in',
  attendanceClockOut: '/hr/attendance/clock-out',
  timesheets: '/hr/timesheets',
  timesheet: (id: string) => `/hr/timesheets/${id}`,
  timesheetApprove: (id: string) => `/hr/timesheets/${id}/approve`,
  timesheetsExportPayrollOt: '/hr/timesheets/export-payroll-ot',
  timesheetsExportToPayroll: '/hr/timesheets/export-to-payroll',
  timesheetsMissingReport: '/hr/timesheets/missing-report',

  advances: '/hr/advances',
  advanceClose: (id: string) => `/hr/advances/${id}/close`,
  loans: '/hr/loans',
  loansOutstandingReport: '/hr/loans/outstanding-report',
  loanApprove: (id: string) => `/hr/loans/${id}/approve`,
  loanReject: (id: string) => `/hr/loans/${id}/reject`,
  loanReview: (id: string) => `/hr/loans/${id}/review`,
  loanSchedule: (id: string) => `/hr/loans/${id}/schedule`,

  evaluationCycles: '/hr/evaluation-cycles',
  evaluationTemplates: '/hr/evaluation-templates',
  evaluationTemplate: (id: string) => `/hr/evaluation-templates/${id}`,
  evaluations: '/hr/evaluations',
  evaluationFinalize: (id: string) => `/hr/evaluations/${id}/finalize`,
  evaluationSubmitManager: (id: string) => `/hr/evaluations/${id}/submit-manager`,
  evaluationSubmitSelf: (id: string) => `/hr/evaluations/${id}/submit-self`,

  letters: '/hr/letters',
  lettersGenerate: '/hr/letters/generate',
  letter: (id: string) => `/hr/letters/${id}`,
  letterPdf: (id: string) => `/hr/letters/${id}/pdf`,
} as const;

export const VESSEL_SCHEDULES_API = {
  list: (vesselId: string) => `/vessels/${vesselId}/schedules`,
  byId: (vesselId: string, scheduleId: string) => `/vessels/${vesselId}/schedules/${scheduleId}`,
} as const;
