import { Link, useParams } from 'react-router-dom';
import { useMemo, useState } from 'react';
import { ArrowLeft, Download, Calendar, Coins, Package, Scale } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { PortalApiError } from '@/lib/portalApiClient';
import {
  PortalAnimatedGrid,
  PortalAnimatedGridItem,
  PortalAnimatedList,
  PortalAnimatedListItem,
  PortalLoadingState,
  PortalPageHeader,
  PortalPanel,
  PortalStatCard,
} from '@/features/portal-auth/components/portal-ui';
import { PortalQuotationDecisionPanel } from '../components/PortalQuotationDecisionPanel';
import { PortalQuotationNegotiationPanel } from '../components/PortalQuotationNegotiationPanel';
import { usePortalQuotation } from '../hooks/usePortalQuotations';
import { portalQuotationsService } from '../services/portalQuotations.service';
import { portalQuoteTotalAmount } from '../utils/portalQuotationStatus';

/** Statuses where a customer-facing PDF is commonly generated by staff. */
const PDF_LIKELY_STATUSES = new Set([
  'APPROVED',
  'SENT',
  'WON',
  'CONVERTED',
  'ACCEPTED',
]);

export default function PortalQuoteDetailPage() {
  const { id = '' } = useParams();
  const { data, isLoading, isError, error, refetch } = usePortalQuotation(id);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [pdfPending, setPdfPending] = useState(false);
  const [pdfUnavailable, setPdfUnavailable] = useState(false);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  const canTryPdf = useMemo(() => {
    if (!data) return false;
    if (data.pdfUrl) return true;
    if (data.pdfReady === true) return true;
    if (data.pdfReady === false) return false;
    const status = (data.status || '').toUpperCase();
    return !status || PDF_LIKELY_STATUSES.has(status);
  }, [data]);

  if (isLoading) {
    return <PortalLoadingState label="Loading quotation…" />;
  }

  if (isError || !data) {
    return (
      <div className="space-y-2">
        <p className="text-sm text-[var(--color-danger-600)]">
          {error instanceof PortalApiError || error instanceof Error
            ? error.message
            : 'Quotation not found.'}
        </p>
        <Button type="button" size="sm" variant="secondary" onClick={() => refetch()}>
          Retry
        </Button>
        <Link to="/portal/quotes" className="block text-sm underline text-[var(--color-primary)]">
          Back to quotes
        </Link>
      </div>
    );
  }

  const showDownload = canTryPdf && !pdfUnavailable;
  const total = portalQuoteTotalAmount(data);

  return (
    <div className="space-y-5">
      <Link
        to="/portal/quotes"
        className="inline-flex items-center gap-1.5 text-xs font-medium text-[var(--color-neutral-500)] hover:text-[var(--color-primary)]"
      >
        <ArrowLeft size={14} aria-hidden="true" />
        Back to quotes
      </Link>
      <PortalPageHeader
        title={data.number}
        description={
          [data.origin, data.destination].filter(Boolean).join(' → ') ||
          data.jobType ||
          'Quotation detail'
        }
        actions={
          <div className="flex flex-wrap items-center gap-2">
            {data.status ? <Badge variant="info">{data.status.replaceAll('_', ' ')}</Badge> : null}
            {total != null ? (
              <Badge variant="neutral">
                {data.currencyCode || 'AED'}{' '}
                {total.toLocaleString(undefined, { maximumFractionDigits: 2 })}
              </Badge>
            ) : null}
            {showDownload ? (
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={pdfPending}
                onClick={() => {
                  setPdfError(null);
                  setPdfPending(true);
                  const quoteId = id || data.id;
                  void portalQuotationsService
                    .downloadPdf(quoteId, data.number || 'quotation')
                    .catch((err) => {
                      setPdfUnavailable(true);
                      setPdfError(
                        err instanceof PortalApiError || err instanceof Error
                          ? err.message
                          : 'PDF is not ready for this quotation yet.',
                      );
                    })
                    .finally(() => setPdfPending(false));
                }}
              >
                <Download size={14} aria-hidden="true" />
                {pdfPending ? 'Downloading…' : 'Download PDF'}
              </Button>
            ) : null}
          </div>
        }
      />

      {actionSuccess ? (
        <p className="text-sm text-[var(--color-success-600)]" role="status">
          {actionSuccess}
        </p>
      ) : null}

      <PortalQuotationDecisionPanel
        quote={data}
        onSuccess={(message) => {
          setActionSuccess(message);
          void refetch();
        }}
      />

      <PortalQuotationNegotiationPanel
        quote={data}
        onSuccess={(message) => {
          setActionSuccess(message);
          void refetch();
        }}
      />

      {data.convertedJobNumber ? (
        <PortalPanel padded className="text-sm">
          <p>
            <span className="text-[var(--color-neutral-500)]">Converted to job: </span>
            <strong>{data.convertedJobNumber}</strong>
          </p>
        </PortalPanel>
      ) : null}

      {data.source ? (
        <p className="text-xs text-[var(--color-neutral-500)]">Source: {data.source.replaceAll('_', ' ')}</p>
      ) : null}

      {(pdfError || !showDownload) && (
        <p
          className={`text-sm ${pdfError ? 'text-[var(--color-neutral-600)]' : 'text-[var(--color-neutral-500)]'}`}
          role={pdfError ? 'status' : undefined}
        >
          {pdfError ||
            'A PDF will appear here once your forwarder generates the customer quotation PDF.'}
        </p>
      )}

      <PortalAnimatedGrid className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <PortalAnimatedGridItem>
          <PortalStatCard label="Currency" value={data.currencyCode || '—'} Icon={Coins} theme="gold" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Valid until" value={data.validUntil || '—'} Icon={Calendar} theme="navy" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Weight" value={data.grossWeight ?? '—'} Icon={Scale} theme="orange" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Pieces" value={data.pieces ?? '—'} Icon={Package} theme="green" />
        </PortalAnimatedGridItem>
      </PortalAnimatedGrid>

      {data.commodity || data.specialRequirements ? (
        <PortalPanel padded className="space-y-2 text-sm">
          {data.commodity ? (
            <p>
              <span className="text-[var(--color-neutral-500)]">Commodity: </span>
              {data.commodity}
            </p>
          ) : null}
          {data.specialRequirements ? (
            <p>
              <span className="text-[var(--color-neutral-500)]">Requirements: </span>
              {data.specialRequirements}
            </p>
          ) : null}
        </PortalPanel>
      ) : null}

      {data.packages?.length ? (
        <PortalPanel padded>
          <h2 className="mb-3 text-sm font-semibold text-[var(--color-neutral-900)]">Packages</h2>
          <div className="space-y-2 text-sm">
            {data.packages.map((pkg, index) => (
              <div key={pkg.id ?? index} className="border-b border-[var(--color-neutral-100)] pb-2 last:border-0">
                {[pkg.lengthCm, pkg.widthCm, pkg.heightCm].every((v) => v != null)
                  ? `${pkg.lengthCm}×${pkg.widthCm}×${pkg.heightCm} cm`
                  : 'Package'}{' '}
                · {pkg.pieces ?? 1} pc · {pkg.grossWeightKg ?? '—'} kg
                {pkg.cbm != null ? ` · ${pkg.cbm} CBM` : ''}
              </div>
            ))}
          </div>
        </PortalPanel>
      ) : null}

      <PortalPanel padded>
        <h2 className="mb-4 text-sm font-semibold text-[var(--color-neutral-900)]">Charge lines</h2>
        {!data.lines?.length ? (
          <p className="text-sm text-[var(--color-neutral-400)]">
            No charge lines yet. Your forwarder will add pricing before sending the quote.
          </p>
        ) : (
          <PortalAnimatedList className="space-y-2">
            {data.lines.map((line) => (
              <PortalAnimatedListItem
                key={line.id}
                className="flex justify-between gap-3 border-b border-[var(--color-neutral-100)] pb-2 text-sm last:border-0"
              >
                <span>{line.description}</span>
                <span className="font-medium tabular-nums">
                  {line.amount != null
                    ? `${line.currencyCode || data.currencyCode || ''} ${line.amount}`
                    : '—'}
                </span>
              </PortalAnimatedListItem>
            ))}
          </PortalAnimatedList>
        )}
      </PortalPanel>
    </div>
  );
}
