import { Link, useParams } from 'react-router-dom';
import { useMemo, useState } from 'react';
import { ArrowLeft, Download, Calendar, Coins, Package, Scale } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { PortalApiError } from '@/lib/portalApiClient';
import {
  PortalAnimatedGrid,
  PortalAnimatedGridItem,
  PortalAnimatedList,
  PortalAnimatedListItem,
  PortalLoadingState,
  PortalPageHeader,
  PortalPanel,
  PortalStatCard,
  portalSelectClassName,
} from '@/features/portal-auth/components/portal-ui';
import {
  useAcceptPortalQuotation,
  usePortalQuotation,
  useRejectPortalQuotation,
} from '../hooks/usePortalQuotations';
import { PORTAL_QUOTATION_REJECT_REASONS } from '../api/portalQuotations.api';
import { portalQuotationsService } from '../services/portalQuotations.service';

/** Statuses where a customer-facing PDF is commonly generated by staff. */
const PDF_LIKELY_STATUSES = new Set([
  'APPROVED',
  'SENT',
  'WON',
  'CONVERTED',
  'ACCEPTED',
]);

export default function PortalQuoteDetailPage() {
  const { id = '' } = useParams();
  const { data, isLoading, isError, error, refetch } = usePortalQuotation(id);
  const acceptQuote = useAcceptPortalQuotation();
  const rejectQuote = useRejectPortalQuotation();
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [pdfPending, setPdfPending] = useState(false);
  const [pdfUnavailable, setPdfUnavailable] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState<(typeof PORTAL_QUOTATION_REJECT_REASONS)[number]>(
    PORTAL_QUOTATION_REJECT_REASONS[0],
  );
  const [rejectNotes, setRejectNotes] = useState('');
  const [showReject, setShowReject] = useState(false);
  const [confirmAccept, setConfirmAccept] = useState(false);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  const canTryPdf = useMemo(() => {
    if (!data) return false;
    if (data.pdfUrl) return true;
    if (data.pdfReady === true) return true;
    if (data.pdfReady === false) return false;
    const status = (data.status || '').toUpperCase();
    return !status || PDF_LIKELY_STATUSES.has(status);
  }, [data]);

  if (isLoading) {
    return <PortalLoadingState label="Loading quotation…" />;
  }

  if (isError || !data) {
    return (
      <div className="space-y-2">
        <p className="text-sm text-[var(--color-danger-600)]">
          {error instanceof PortalApiError || error instanceof Error
            ? error.message
            : 'Quotation not found.'}
        </p>
        <Button type="button" size="sm" variant="secondary" onClick={() => refetch()}>
          Retry
        </Button>
        <Link to="/portal/quotes" className="block text-sm underline text-[var(--color-primary)]">
          Back to quotes
        </Link>
      </div>
    );
  }

  const showDownload = canTryPdf && !pdfUnavailable;
  const statusUpper = (data.status || '').toUpperCase();
  const canDecide = statusUpper === 'SENT';
  const actionPending = acceptQuote.isPending || rejectQuote.isPending;

  return (
    <div className="space-y-5">
      <Link
        to="/portal/quotes"
        className="inline-flex items-center gap-1.5 text-xs font-medium text-[var(--color-neutral-500)] hover:text-[var(--color-primary)]"
      >
        <ArrowLeft size={14} aria-hidden="true" />
        Back to quotes
      </Link>
      <PortalPageHeader
        title={data.number}
        description={
          [data.origin, data.destination].filter(Boolean).join(' → ') ||
          data.jobType ||
          'Quotation detail'
        }
        actions={
          <div className="flex flex-wrap items-center gap-2">
            {data.status ? <Badge variant="info">{data.status}</Badge> : null}
            {canDecide ? (
              <>
                <Button
                  type="button"
                  size="sm"
                  disabled={actionPending}
                  onClick={() => {
                    setActionError(null);
                    setActionSuccess(null);
                    if (!confirmAccept) {
                      setConfirmAccept(true);
                      return;
                    }
                    void acceptQuote
                      .mutateAsync(id || data.id)
                      .then(() => {
                        setConfirmAccept(false);
                        setActionSuccess('Quotation accepted.');
                      })
                      .catch((err) => {
                        setActionError(
                          err instanceof PortalApiError || err instanceof Error
                            ? err.message
                            : 'Could not accept quotation.',
                        );
                      });
                  }}
                >
                  {acceptQuote.isPending
                    ? 'Accepting…'
                    : confirmAccept
                      ? 'Confirm accept'
                      : 'Accept quote'}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant="secondary"
                  disabled={actionPending}
                  onClick={() => {
                    setConfirmAccept(false);
                    setShowReject((v) => !v);
                  }}
                >
                  Reject
                </Button>
              </>
            ) : null}
            {showDownload ? (
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={pdfPending}
                onClick={() => {
                  setPdfError(null);
                  setPdfPending(true);
                  const quoteId = id || data.id;

                  // Always fetch via portal API (Bearer). Do not navigate to
                  // relative pdf_url paths — those hit the SPA and show 404.
                  void portalQuotationsService
                    .downloadPdf(quoteId, data.number || 'quotation')
                    .catch((err) => {
                      setPdfUnavailable(true);
                      setPdfError(
                        err instanceof PortalApiError || err instanceof Error
                          ? err.message
                          : 'PDF is not ready for this quotation yet.',
                      );
                    })
                    .finally(() => setPdfPending(false));
                }}
              >
                <Download size={14} aria-hidden="true" />
                {pdfPending ? 'Downloading…' : 'Download PDF'}
              </Button>
            ) : null}
          </div>
        }
      />

      {actionError ? (
        <p className="text-sm text-[var(--color-danger-600)]" role="alert">
          {actionError}
        </p>
      ) : null}
      {actionSuccess ? (
        <p className="text-sm text-[var(--color-success-600)]" role="status">
          {actionSuccess}
        </p>
      ) : null}

      {canDecide && showReject ? (
        <PortalPanel padded className="space-y-3">
          <p className="text-sm font-medium text-[var(--color-neutral-800)]">Reject this quotation</p>
          <label className="block text-sm">
            <span className="mb-1 block text-xs font-medium text-[var(--color-neutral-600)]">
              Reason
            </span>
            <select
              className={portalSelectClassName}
              value={rejectReason}
              onChange={(e) =>
                setRejectReason(e.target.value as (typeof PORTAL_QUOTATION_REJECT_REASONS)[number])
              }
            >
              {PORTAL_QUOTATION_REJECT_REASONS.map((reason) => (
                <option key={reason} value={reason}>
                  {reason}
                </option>
              ))}
            </select>
          </label>
          <label className="block text-sm">
            <span className="mb-1 block text-xs font-medium text-[var(--color-neutral-600)]">
              Notes (optional)
            </span>
            <textarea
              className="min-h-[72px] w-full rounded-md border border-[var(--color-neutral-200)] px-3 py-2 text-sm"
              maxLength={500}
              value={rejectNotes}
              onChange={(e) => setRejectNotes(e.target.value)}
            />
          </label>
          <Button
            type="button"
            size="sm"
            disabled={actionPending}
            onClick={() => {
              setActionError(null);
              void rejectQuote
                .mutateAsync({
                  id: id || data.id,
                  dto: {
                    reason: rejectReason,
                    notes: rejectNotes.trim() || undefined,
                  },
                })
                .then(() => {
                  setShowReject(false);
                  setActionSuccess('Quotation rejected.');
                })
                .catch((err) => {
                  setActionError(
                    err instanceof PortalApiError || err instanceof Error
                      ? err.message
                      : 'Could not reject quotation.',
                  );
                });
            }}
          >
            {rejectQuote.isPending ? 'Rejecting…' : 'Confirm reject'}
          </Button>
        </PortalPanel>
      ) : null}

      {(pdfError || !showDownload) && (
        <p
          className={`text-sm ${pdfError ? 'text-[var(--color-neutral-600)]' : 'text-[var(--color-neutral-500)]'}`}
          role={pdfError ? 'status' : undefined}
        >
          {pdfError ||
            'A PDF will appear here once your forwarder generates the customer quotation PDF.'}
        </p>
      )}

      <PortalAnimatedGrid className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <PortalAnimatedGridItem>
          <PortalStatCard label="Currency" value={data.currencyCode || '—'} Icon={Coins} theme="gold" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Valid until" value={data.validUntil || '—'} Icon={Calendar} theme="navy" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Weight" value={data.grossWeight ?? '—'} Icon={Scale} theme="orange" />
        </PortalAnimatedGridItem>
        <PortalAnimatedGridItem>
          <PortalStatCard label="Pieces" value={data.pieces ?? '—'} Icon={Package} theme="green" />
        </PortalAnimatedGridItem>
      </PortalAnimatedGrid>

      {data.commodity || data.specialRequirements ? (
        <PortalPanel padded className="space-y-2 text-sm">
          {data.commodity ? (
            <p>
              <span className="text-[var(--color-neutral-500)]">Commodity: </span>
              {data.commodity}
            </p>
          ) : null}
          {data.specialRequirements ? (
            <p>
              <span className="text-[var(--color-neutral-500)]">Requirements: </span>
              {data.specialRequirements}
            </p>
          ) : null}
        </PortalPanel>
      ) : null}

      <PortalPanel padded>
        <h2 className="mb-4 text-sm font-semibold text-[var(--color-neutral-900)]">Lines</h2>
        {!data.lines?.length ? (
          <p className="text-sm text-[var(--color-neutral-400)]">No charge lines.</p>
        ) : (
          <PortalAnimatedList className="space-y-2">
            {data.lines.map((line) => (
              <PortalAnimatedListItem
                key={line.id}
                className="flex justify-between gap-3 border-b border-[var(--color-neutral-100)] pb-2 text-sm last:border-0"
              >
                <span>{line.description}</span>
                <span className="font-medium tabular-nums">
                  {line.amount != null
                    ? `${line.currencyCode || data.currencyCode || ''} ${line.amount}`
                    : '—'}
                </span>
              </PortalAnimatedListItem>
            ))}
          </PortalAnimatedList>
        )}
      </PortalPanel>
    </div>
  );
}
