import {
  BookOpen,
  FileText,
  BarChart2,
  CalendarCheck,
  ListChecks,
  Search,
  MapPin,
  Inbox,
  Users,
} from 'lucide-react';
import type { MenuTile } from '../types/menu.types';

export const customerServiceMenu: MenuTile[] = [
  {
    id: 'portal-inbox',
    title: 'Portal Inbox',
    description: 'Customer portal messages, disputes, and credit limit requests.',
    icon: Inbox,
    iconColor: 'bg-indigo-500',
    path: '/portal-admin/inbox',
    section: 'Customer Portal',
  },
  {
    id: 'portal-users',
    title: 'Customer Portal Users',
    description: 'Tenant-wide list of customer portal logins (invite from party detail).',
    icon: Users,
    iconColor: 'bg-violet-500',
    path: '/portal-users',
    section: 'Customer Portal',
  },
  {
    id: 'all-shipments',
    title: 'All Shipments',
    description: 'View all shipments by salesperson, customer, and department.',
    icon: BookOpen,
    iconColor: 'bg-sky-500',
    path: '/customer-service/shipments',
    section: 'Customer Service',
  },
  {
    id: 'enquiry-sheet',
    title: 'Enquiry Sheet',
    description: 'Maintain client enquiries regarding cargo movement.',
    icon: FileText,
    iconColor: 'bg-sky-500',
    path: '/customer-service/enquiry-sheet',
    section: 'Customer Service',
  },
  {
    id: 'pricing-dashboard',
    title: 'Pricing Dashboard',
    description: 'View open enquiry reports and status-wise statistics.',
    icon: BarChart2,
    iconColor: 'bg-emerald-500',
    path: '/customer-service/pricing-dashboard',
    section: 'Customer Service',
  },
  {
    id: 'sailing-schedule',
    title: 'Sailing Schedule',
    description: 'Create weekly or monthly schedules for cargo movement.',
    icon: CalendarCheck,
    iconColor: 'bg-emerald-500',
    path: '/customer-service/sailing-schedule',
    section: 'Customer Service',
  },
  {
    id: 'shipment-agent-edi',
    title: 'Shipment - Agent EDI',
    description: 'Generate and download the agent EDI XML file.',
    icon: ListChecks,
    iconColor: 'bg-lime-600',
    path: '/customer-service/agent-edi',
    section: 'Customer Service',
  },
  {
    id: 'shipment-costing-search',
    title: 'Shipment Costing Search',
    description: 'View shipments with charges and shipment details.',
    icon: Search,
    iconColor: 'bg-amber-500',
    path: '/customer-service/costing-search',
    section: 'Customer Service',
  },
  {
    id: 'shipment-tracking',
    title: 'Shipment Tracking',
    description: 'Track shipment status across the company and partners.',
    icon: MapPin,
    iconColor: 'bg-amber-500',
    path: '/customer-service/tracking',
    section: 'Customer Service',
  },
];
