export const CRM_API = {
  leads: '/crm/leads',
  lead: (id: string) => `/crm/leads/${id}`,
  leadConvert: (id: string) => `/crm/leads/${id}/convert`,
  leadImport: '/crm/leads/import',
  leadPipeline: '/crm/leads/pipeline',
  callLogs: '/crm/call-logs',
  dailyCallLogs: '/crm/call-logs/daily',
  followUps: '/crm/follow-ups',
  followUp: (id: string) => `/crm/follow-ups/${id}`,
  followUpCalendar: '/crm/follow-ups/calendar',
  enquiries: '/crm/enquiries',
  enquiry: (id: string) => `/crm/enquiries/${id}`,
  enquiryConvert: (id: string) => `/crm/enquiries/${id}/convert-to-quote`,
  dashboard: '/crm/dashboard',
  budgets: '/crm/budgets',
  report: (type: string) => `/crm/reports/${type}`,
  subscribers: '/crm/subscribers',
  subscriberImport: '/crm/subscribers/import',
  unsubscribe: (id: string) => `/crm/subscribers/${id}/unsubscribe`,
  templates: '/crm/campaign-templates',
  campaigns: '/crm/campaigns',
  campaignSchedule: (id: string) => `/crm/campaigns/${id}/schedule`,
  campaignSend: (id: string) => `/crm/campaigns/${id}/send`,
} as const;
