/** Common freight / ERP department labels for Masters → Departments. */
export const DEPARTMENT_NAME_SUGGESTIONS = [
  'Human Resources',
  'Finance',
  'Accounts',
  'Sales',
  'Marketing',
  'Customer Service',
  'Customer Support',
  'Operations',
  'Documentation',
  'Export',
  'Import',
  'Air Export',
  'Air Import',
  'Sea Export',
  'Sea Import',
  'Logistics',
  'Warehouse',
  'Procurement',
  'Purchasing',
  'IT',
  'Information Technology',
  'Administration',
  'Management',
  'Legal',
  'Compliance',
  'Quality Assurance',
  'Business Development',
  'Pricing',
  'Commercial',
  'Billing',
  'Collections',
  'Transport',
  'Trucking',
  'Customs',
  'Branch Office',
  'Head Office',
] as const;

export const DEPARTMENT_NAME_OPTIONS: Array<{ value: string; label: string }> =
  DEPARTMENT_NAME_SUGGESTIONS.map((name) => ({ value: name, label: name }));
