/** Common ERP / logistics designation (job title) labels. */
export const DESIGNATION_NAME_SUGGESTIONS = [
  'Managing Director',
  'General Manager',
  'Branch Manager',
  'Operations Manager',
  'Export Manager',
  'Import Manager',
  'Sales Manager',
  'Sales Executive',
  'Business Development Manager',
  'Customer Service Manager',
  'Customer Service Executive',
  'Documentation Officer',
  'Documentation Executive',
  'Logistics Executive',
  'Logistics Manager',
  'Warehouse Manager',
  'Warehouse Supervisor',
  'Accountant',
  'Accounts Manager',
  'Finance Manager',
  'HR Manager',
  'HR Executive',
  'Admin Manager',
  'Admin Executive',
  'IT Manager',
  'Software Engineer',
  'Pricing Executive',
  'Commercial Manager',
  'Team Lead',
  'Supervisor',
  'Executive',
  'Officer',
  'Assistant',
  'Coordinator',
  'Clerk',
  'Driver',
  'Customs Clearance Officer',
] as const;

export const DESIGNATION_NAME_OPTIONS: Array<{ value: string; label: string }> =
  DESIGNATION_NAME_SUGGESTIONS.map((name) => ({ value: name, label: name }));
